import {
  Activity,
  Apple,
  ArrowLeft,
  ArrowRight,
  Atom,
  Award,
  Backpack,
  Beef,
  Bird,
  Bomb,
  Box,
  BrainCircuit,
  CakeSlice,
  Castle,
  Cat,
  CircleHelp,
  Coins,
  Compass,
  Crosshair,
  Crown,
  CupSoda,
  Diamond,
  DiamondPlus,
  Dices,
  Dog,
  Fish,
  Flag,
  Flame,
  FlameKindling,
  Gem,
  Ghost,
  GlassWater,
  Globe,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Hourglass,
  Key,
  Map,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  MoonStar,
  Mountain,
  Package,
  PawPrint,
  PiggyBank,
  PillBottle,
  Pizza,
  Rabbit,
  Save,
  Settings,
  Shield,
  ShoppingCart,
  Signpost,
  Skull,
  Soup,
  Sparkle,
  Sparkles,
  Star,
  Sword,
  Swords,
  Target,
  Timer,
  Trees,
  Trophy,
  Turtle,
  Users,
  Wand,
  WandSparkles,
  Wine,
  Worm,
  Zap,
} from "lucide-react";

export const icons = [
  // Combat & Action
  { name: "Sword", category: "combat", component: Sword },
  { name: "Shield", category: "combat", component: Shield },
  { name: "Target", category: "combat", component: Target },
  { name: "Crosshair", category: "combat", component: Crosshair },
  { name: "Wand", category: "combat", component: Wand },
  { name: "WandSparkles", category: "combat", component: WandSparkles },
  { name: "Flame", category: "combat", component: Flame },
  { name: "Zap", category: "combat", component: Zap },
  { name: "Bomb", category: "combat", component: Bomb },
  { name: "Swords", category: "combat", component: Swords },

  // Character Status & Progression
  { name: "Heart", category: "status", component: Heart },
  { name: "HeartPulse", category: "status", component: HeartPulse },
  { name: "Trophy", category: "status", component: Trophy },
  { name: "Medal", category: "status", component: Medal },
  { name: "Crown", category: "status", component: Crown },
  { name: "Star", category: "status", component: Star },
  { name: "Hourglass", category: "status", component: Hourglass },
  { name: "Timer", category: "status", component: Timer },
  { name: "Award", category: "status", component: Award },
  { name: "Activity", category: "status", component: Activity },

  // Inventory & Resources
  { name: "Backpack", category: "inventory", component: Backpack },
  { name: "Coins", category: "inventory", component: Coins },
  { name: "Gem", category: "inventory", component: Gem },
  { name: "Package", category: "inventory", component: Package },
  { name: "ShoppingCart", category: "inventory", component: ShoppingCart },
  { name: "PiggyBank", category: "inventory", component: PiggyBank },
  { name: "Key", category: "inventory", component: Key },
  { name: "Box", category: "inventory", component: Box },
  { name: "Diamond", category: "inventory", component: Diamond },

  // Navigation & World
  { name: "Map", category: "navigation", component: Map },
  { name: "MapPin", category: "navigation", component: MapPin },
  { name: "Compass", category: "navigation", component: Compass },
  { name: "Mountain", category: "navigation", component: Mountain },
  { name: "Castle", category: "navigation", component: Castle },
  { name: "Home", category: "navigation", component: Home },
  { name: "Trees", category: "navigation", component: Trees },
  { name: "Flag", category: "navigation", component: Flag },
  { name: "Globe", category: "navigation", component: Globe },
  { name: "Signpost", category: "navigation", component: Signpost },

  // UI Elements
  { name: "Menu", category: "ui", component: Menu },
  { name: "Settings", category: "ui", component: Settings },
  { name: "ArrowLeft", category: "ui", component: ArrowLeft },
  { name: "ArrowRight", category: "ui", component: ArrowRight },
  { name: "Save", category: "ui", component: Save },
  { name: "MessageCircle", category: "ui", component: MessageCircle },
  { name: "Users", category: "ui", component: Users },
  { name: "Handshake", category: "ui", component: Handshake },
  { name: "CircleHelp", category: "ui", component: CircleHelp },

  // Magic & Fantasy
  { name: "Sparkles", category: "magic", component: Sparkles },
  { name: "Ghost", category: "magic", component: Ghost },
  { name: "Skull", category: "magic", component: Skull },
  { name: "BrainCircuit", category: "magic", component: BrainCircuit },
  { name: "MoonStar", category: "magic", component: MoonStar },
  { name: "FlameKindling", category: "magic", component: FlameKindling },
  { name: "Atom", category: "magic", component: Atom },
  { name: "DiamondPlus", category: "magic", component: DiamondPlus },
  { name: "Sparkle", category: "magic", component: Sparkle },
  { name: "Dices", category: "magic", component: Dices },

  // Consumables
  { name: "Apple", category: "consumables", component: Apple },
  { name: "GlassWater", category: "consumables", component: GlassWater },
  { name: "Beef", category: "consumables", component: Beef },
  { name: "CakeSlice", category: "consumables", component: CakeSlice },
  { name: "PillBottle", category: "consumables", component: PillBottle },
  { name: "Wine", category: "consumables", component: Wine },
  { name: "Pizza", category: "consumables", component: Pizza },
  { name: "Soup", category: "consumables", component: Soup },
  { name: "CupSoda", category: "consumables", component: CupSoda },

  // Creatures & Characters
  { name: "Ghost", category: "creatures", component: Ghost },
  { name: "Skull", category: "creatures", component: Skull },
  { name: "Bird", category: "creatures", component: Bird },
  { name: "Cat", category: "creatures", component: Cat },
  { name: "Dog", category: "creatures", component: Dog },
  { name: "Fish", category: "creatures", component: Fish },
  { name: "PawPrint", category: "creatures", component: PawPrint },
  { name: "Rabbit", category: "creatures", component: Rabbit },
  { name: "Turtle", category: "creatures", component: Turtle },
  { name: "Worm", category: "creatures", component: Worm },
];
