import {
  AArrowDown,
  AArrowUp,
  ALargeSmall,
  Accessibility,
  Activity,
  AirVent,
  Airplay,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlarmSmoke,
  Album,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalDistributeEnd,
  AlignHorizontalDistributeStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignJustify,
  AlignLeft,
  AlignRight,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  AlignVerticalDistributeEnd,
  AlignVerticalDistributeStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalSpaceAround,
  AlignVerticalSpaceBetween,
  Ambulance,
  Ampersand,
  Ampersands,
  Anchor,
  Angry,
  Annoyed,
  Antenna,
  Anvil,
  Aperture,
  AppWindow,
  AppWindowMac,
  Apple,
  Archive,
  ArchiveRestore,
  ArchiveX,
  AreaChart,
  Armchair,
  ArrowBigDown,
  ArrowBigDownDash,
  ArrowBigLeft,
  ArrowBigLeftDash,
  ArrowBigRight,
  ArrowBigRightDash,
  ArrowBigUp,
  ArrowBigUpDash,
  ArrowDown,
  ArrowDown01,
  ArrowDown10,
  ArrowDownAZ,
  ArrowDownFromLine,
  ArrowDownLeft,
  ArrowDownNarrowWide,
  ArrowDownRight,
  ArrowDownToDot,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowDownZA,
  ArrowLeft,
  ArrowLeftFromLine,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightFromLine,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUp01,
  ArrowUp10,
  ArrowUpAZ,
  ArrowUpDown,
  ArrowUpFromDot,
  ArrowUpFromLine,
  ArrowUpLeft,
  ArrowUpNarrowWide,
  ArrowUpRight,
  ArrowUpToLine,
  ArrowUpWideNarrow,
  ArrowUpZA,
  ArrowsUpFromLine,
  Asterisk,
  AtSign,
  Atom,
  AudioLines,
  AudioWaveform,
  Award,
  Axe,
  Axis3d,
  Baby,
  Backpack,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeHelp,
  BadgeIndianRupee,
  BadgeInfo,
  BadgeJapaneseYen,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgePoundSterling,
  BadgeRussianRuble,
  BadgeSwissFranc,
  BadgeX,
  BaggageClaim,
  Ban,
  Banana,
  Banknote,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  BarChartBig,
  BarChartHorizontal,
  BarChartHorizontalBig,
  Barcode,
  Baseline,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Beaker,
  Bean,
  BeanOff,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  Beer,
  BeerOff,
  Bell,
  BellDot,
  BellElectric,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  BicepsFlexed,
  Bike,
  Binary,
  Biohazard,
  Bird,
  Bitcoin,
  Blend,
  Blinds,
  Blocks,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Bolt,
  Bomb,
  Bone,
  Book,
  BookA,
  BookAudio,
  BookCheck,
  BookCopy,
  BookDashed,
  BookDown,
  BookHeadphones,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookText,
  BookType,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkPlus,
  BookmarkX,
  BoomBox,
  Bot,
  BotMessageSquare,
  BotOff,
  Box,
  BoxSelect,
  Boxes,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  BrainCog,
  BrickWall,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseMedical,
  BringToFront,
  Brush,
  Bug,
  BugOff,
  BugPlay,
  Building,
  Building2,
  Bus,
  BusFront,
  Cable,
  CableCar,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarMinus,
  CalendarMinus2,
  CalendarOff,
  CalendarPlus,
  CalendarPlus2,
  CalendarRange,
  CalendarSearch,
  CalendarX,
  CalendarX2,
  Camera,
  CameraOff,
  CandlestickChart,
  Candy,
  CandyCane,
  CandyOff,
  Cannabis,
  Captions,
  CaptionsOff,
  Car,
  CarFront,
  CarTaxiFront,
  Caravan,
  Carrot,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  CassetteTape,
  Cast,
  Castle,
  Cat,
  Cctv,
  Check,
  CheckCheck,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsLeftRight,
  ChevronsRight,
  ChevronsRightLeft,
  ChevronsUp,
  ChevronsUpDown,
  Chrome,
  Church,
  Cigarette,
  CigaretteOff,
  Circle,
  CircleAlert,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowOutDownLeft,
  CircleArrowOutDownRight,
  CircleArrowOutUpLeft,
  CircleArrowOutUpRight,
  CircleArrowRight,
  CircleArrowUp,
  CircleCheck,
  CircleCheckBig,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDashed,
  CircleDivide,
  CircleDollarSign,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CircleEqual,
  CircleFadingPlus,
  CircleGauge,
  CircleHelp,
  CircleMinus,
  CircleOff,
  CircleParking,
  CircleParkingOff,
  CirclePause,
  CirclePercent,
  CirclePlay,
  CirclePlus,
  CirclePower,
  CircleSlash,
  CircleSlash2,
  CircleStop,
  CircleUser,
  CircleUserRound,
  CircleX,
  CircuitBoard,
  Citrus,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardMinus,
  ClipboardPaste,
  ClipboardPen,
  ClipboardPenLine,
  ClipboardPlus,
  ClipboardType,
  ClipboardX,
  Clock,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  ClockArrowDown,
  ClockArrowUp,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  CloudUpload,
  Cloudy,
  Clover,
  Club,
  Code,
  CodeXml,
  Codepen,
  Codesandbox,
  Coffee,
  Cog,
  Coins,
  Columns2,
  Columns3,
  Columns4,
  Combine,
  Command,
  Compass,
  Component,
  Computer,
  ConciergeBell,
  Cone,
  Construction,
  Contact,
  ContactRound,
  Container,
  Contrast,
  Cookie,
  CookingPot,
  Copy,
  CopyCheck,
  CopyMinus,
  CopyPlus,
  CopySlash,
  CopyX,
  Copyleft,
  Copyright,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreativeCommons,
  CreditCard,
  Croissant,
  Crop,
  Cross,
  Crosshair,
  Crown,
  Cuboid,
  CupSoda,
  Currency,
  Cylinder,
  Database,
  DatabaseBackup,
  DatabaseZap,
  Delete,
  Dessert,
  Diameter,
  Diamond,
  DiamondMinus,
  DiamondPercent,
  DiamondPlus,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dices,
  Diff,
  Disc,
  Disc2,
  Disc3,
  DiscAlbum,
  Divide,
  Dna,
  DnaOff,
  Dock,
  Dog,
  DollarSign,
  Donut,
  DoorClosed,
  DoorOpen,
  Dot,
  Download,
  DraftingCompass,
  Drama,
  Dribbble,
  Drill,
  Droplet,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  EarOff,
  Earth,
  EarthLock,
  Eclipse,
  Egg,
  EggFried,
  EggOff,
  Ellipsis,
  EllipsisVertical,
  Equal,
  EqualNot,
  Eraser,
  Euro,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Factory,
  Fan,
  FastForward,
  Feather,
  Fence,
  FerrisWheel,
  Figma,
  File,
  FileArchive,
  FileAudio,
  FileAudio2,
  FileAxis3d,
  FileBadge,
  FileBadge2,
  FileBarChart,
  FileBarChart2,
  FileBox,
  FileCheck,
  FileCheck2,
  FileClock,
  FileCode,
  FileCode2,
  FileCog,
  FileDiff,
  FileDigit,
  FileDown,
  FileHeart,
  FileImage,
  FileInput,
  FileJson,
  FileJson2,
  FileKey,
  FileKey2,
  FileLineChart,
  FileLock,
  FileLock2,
  FileMinus,
  FileMinus2,
  FileMusic,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePieChart,
  FilePlus,
  FilePlus2,
  FileQuestion,
  FileScan,
  FileSearch,
  FileSearch2,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FileVideo,
  FileVideo2,
  FileVolume,
  FileVolume2,
  FileWarning,
  FileX,
  FileX2,
  Files,
  Film,
  Filter,
  FilterX,
  Fingerprint,
  FireExtinguisher,
  Fish,
  FishOff,
  FishSymbol,
  Flag,
  FlagOff,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  FlameKindling,
  Flashlight,
  FlashlightOff,
  FlaskConical,
  FlaskConicalOff,
  FlaskRound,
  FlipHorizontal,
  FlipHorizontal2,
  FlipVertical,
  FlipVertical2,
  Flower,
  Flower2,
  Focus,
  FoldHorizontal,
  FoldVertical,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCode,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPen,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSearch2,
  FolderSymlink,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Folders,
  Footprints,
  Forklift,
  Forward,
  Frame,
  Framer,
  Frown,
  Fuel,
  Fullscreen,
  GalleryHorizontal,
  GalleryHorizontalEnd,
  GalleryThumbnails,
  GalleryVertical,
  GalleryVerticalEnd,
  Gamepad,
  Gamepad2,
  GanttChart,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitBranchPlus,
  GitCommitHorizontal,
  GitCommitVertical,
  GitCompare,
  GitCompareArrows,
  GitFork,
  GitGraph,
  GitMerge,
  GitPullRequest,
  GitPullRequestArrow,
  GitPullRequestClosed,
  GitPullRequestCreate,
  GitPullRequestCreateArrow,
  GitPullRequestDraft,
  Github,
  Gitlab,
  GlassWater,
  Glasses,
  Globe,
  GlobeLock,
  Goal,
  Grab,
  GraduationCap,
  Grape,
  Grid2x2,
  Grid2x2Check,
  Grid2x2X,
  Grid3x3,
  Grip,
  GripHorizontal,
  GripVertical,
  Group,
  Guitar,
  Ham,
  Hammer,
  Hand,
  HandCoins,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  HardHat,
  Hash,
  Haze,
  HdmiPort,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Heater,
  Hexagon,
  Highlighter,
  History,
  Hop,
  HopOff,
  Hospital,
  Hotel,
  Hourglass,
  House,
  HousePlug,
  HousePlus,
  IceCreamBowl,
  IceCreamCone,
  Image,
  ImageDown,
  ImageMinus,
  ImageOff,
  ImagePlay,
  ImagePlus,
  ImageUp,
  Images,
  Import,
  Inbox,
  IndentDecrease,
  IndentIncrease,
  IndianRupee,
  Infinity,
  Info,
  InspectionPanel,
  Instagram,
  Italic,
  IterationCcw,
  IterationCw,
  JapaneseYen,
  Joystick,
  Kanban,
  Key,
  KeyRound,
  KeySquare,
  Keyboard,
  KeyboardMusic,
  KeyboardOff,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  LandPlot,
  Landmark,
  Languages,
  Laptop,
  LaptopMinimal,
  Lasso,
  LassoSelect,
  Laugh,
  Layers,
  Layers2,
  Layers3,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Leaf,
  LeafyGreen,
  Lectern,
  Library,
  LibraryBig,
  LifeBuoy,
  Ligature,
  Lightbulb,
  LightbulbOff,
  LineChart,
  Link,
  Link2,
  Link2Off,
  Linkedin,
  List,
  ListCheck,
  ListChecks,
  ListCollapse,
  ListEnd,
  ListFilter,
  ListMinus,
  ListMusic,
  ListOrdered,
  ListPlus,
  ListRestart,
  ListStart,
  ListTodo,
  ListTree,
  ListVideo,
  ListX,
  Loader,
  LoaderCircle,
  LoaderPinwheel,
  Locate,
  LocateFixed,
  LocateOff,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  LogIn,
  LogOut,
  Logs,
  Lollipop,
  Luggage,
  Magnet,
  Mail,
  MailCheck,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestion,
  MailSearch,
  MailWarning,
  MailX,
  Mailbox,
  Mails,
  Map,
  MapPin,
  MapPinOff,
  MapPinned,
  Martini,
  Maximize,
  Maximize2,
  Medal,
  Megaphone,
  MegaphoneOff,
  Meh,
  MemoryStick,
  Menu,
  Merge,
  MessageCircle,
  MessageCircleCode,
  MessageCircleDashed,
  MessageCircleHeart,
  MessageCircleMore,
  MessageCircleOff,
  MessageCirclePlus,
  MessageCircleQuestion,
  MessageCircleReply,
  MessageCircleWarning,
  MessageCircleX,
  MessageSquare,
  MessageSquareCode,
  MessageSquareDashed,
  MessageSquareDiff,
  MessageSquareDot,
  MessageSquareHeart,
  MessageSquareMore,
  MessageSquareOff,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareReply,
  MessageSquareShare,
  MessageSquareText,
  MessageSquareWarning,
  MessageSquareX,
  MessagesSquare,
  Mic,
  MicOff,
  MicVocal,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  MilkOff,
  Minimize,
  Minimize2,
  Minus,
  Monitor,
  MonitorCheck,
  MonitorCog,
  MonitorDot,
  MonitorDown,
  MonitorOff,
  MonitorPause,
  MonitorPlay,
  MonitorSmartphone,
  MonitorSpeaker,
  MonitorStop,
  MonitorUp,
  MonitorX,
  Moon,
  MoonStar,
  Mountain,
  MountainSnow,
  Mouse,
  MouseOff,
  MousePointer,
  MousePointer2,
  MousePointerBan,
  MousePointerClick,
  Move,
  Move3d,
  MoveDiagonal,
  MoveDiagonal2,
  MoveDown,
  MoveDownLeft,
  MoveDownRight,
  MoveHorizontal,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveUpLeft,
  MoveUpRight,
  MoveVertical,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Navigation2Off,
  NavigationOff,
  Network,
  Newspaper,
  Nfc,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  NotepadTextDashed,
  Nut,
  NutOff,
  Octagon,
  OctagonAlert,
  OctagonPause,
  OctagonX,
  Option,
  Orbit,
  Origami,
  Package,
  Package2,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  PaintbrushVertical,
  Palette,
  PanelBottom,
  PanelBottomClose,
  PanelBottomDashed,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftDashed,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightDashed,
  PanelRightOpen,
  PanelTop,
  PanelTopClose,
  PanelTopDashed,
  PanelTopOpen,
  PanelsLeftBottom,
  PanelsRightBottom,
  PanelsTopLeft,
  Paperclip,
  Parentheses,
  ParkingMeter,
  PartyPopper,
  Pause,
  PawPrint,
  PcCase,
  Pen,
  PenLine,
  PenOff,
  PenTool,
  Pencil,
  PencilLine,
  PencilOff,
  PencilRuler,
  Pentagon,
  Percent,
  PersonStanding,
  PhilippinePeso,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  Piano,
  Pickaxe,
  PictureInPicture,
  PictureInPicture2,
  PieChart,
  PiggyBank,
  Pilcrow,
  PilcrowLeft,
  PilcrowRight,
  Pill,
  PillBottle,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  Plug,
  Plug2,
  PlugZap,
  Plus,
  Pocket,
  PocketKnife,
  Podcast,
  Pointer,
  PointerOff,
  Popcorn,
  Popsicle,
  PoundSterling,
  Power,
  PowerOff,
  Presentation,
  Printer,
  PrinterCheck,
  Projector,
  Proportions,
  Puzzle,
  Pyramid,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radiation,
  Radical,
  Radio,
  RadioReceiver,
  RadioTower,
  Radius,
  RailSymbol,
  Rainbow,
  Rat,
  Ratio,
  Receipt,
  ReceiptCent,
  ReceiptEuro,
  ReceiptIndianRupee,
  ReceiptJapaneseYen,
  ReceiptPoundSterling,
  ReceiptRussianRuble,
  ReceiptSwissFranc,
  ReceiptText,
  RectangleEllipsis,
  RectangleHorizontal,
  RectangleVertical,
  Recycle,
  Redo,
  Redo2,
  RedoDot,
  RefreshCcw,
  RefreshCcwDot,
  RefreshCw,
  RefreshCwOff,
  Refrigerator,
  Regex,
  RemoveFormatting,
  Repeat,
  Repeat1,
  Repeat2,
  Replace,
  ReplaceAll,
  Reply,
  ReplyAll,
  Rewind,
  Ribbon,
  Rocket,
  RockingChair,
  RollerCoaster,
  Rotate3d,
  RotateCcw,
  RotateCcwSquare,
  RotateCw,
  RotateCwSquare,
  Route,
  RouteOff,
  Router,
  Rows2,
  Rows3,
  Rows4,
  Rss,
  Ruler,
  RussianRuble,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Save,
  SaveAll,
  SaveOff,
  Scale,
  Scale3d,
  Scaling,
  Scan,
  ScanBarcode,
  ScanEye,
  ScanFace,
  ScanLine,
  ScanQrCode,
  ScanSearch,
  ScanText,
  ScatterChart,
  School,
  Scissors,
  ScissorsLineDashed,
  ScreenShare,
  ScreenShareOff,
  Scroll,
  ScrollText,
  Search,
  SearchCheck,
  SearchCode,
  SearchSlash,
  SearchX,
  Section,
  Send,
  SendHorizontal,
  SendToBack,
  SeparatorHorizontal,
  SeparatorVertical,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Settings,
  Settings2,
  Shapes,
  Share,
  Share2,
  Sheet,
  Shell,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldEllipsis,
  ShieldHalf,
  ShieldMinus,
  ShieldOff,
  ShieldPlus,
  ShieldQuestion,
  ShieldX,
  Ship,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrink,
  Shrub,
  Shuffle,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Signature,
  Signpost,
  SignpostBig,
  Siren,
  SkipBack,
  SkipForward,
  Skull,
  Slack,
  Slash,
  Slice,
  SlidersHorizontal,
  SlidersVertical,
  Smartphone,
  SmartphoneCharging,
  SmartphoneNfc,
  Smile,
  SmilePlus,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Space,
  Spade,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  SpellCheck,
  SpellCheck2,
  Spline,
  Split,
  SprayCan,
  Sprout,
  Square,
  SquareActivity,
  SquareArrowDown,
  SquareArrowDownLeft,
  SquareArrowDownRight,
  SquareArrowLeft,
  SquareArrowOutDownLeft,
  SquareArrowOutDownRight,
  SquareArrowOutUpLeft,
  SquareArrowOutUpRight,
  SquareArrowRight,
  SquareArrowUp,
  SquareArrowUpLeft,
  SquareArrowUpRight,
  SquareAsterisk,
  SquareBottomDashedScissors,
  SquareCheck,
  SquareCheckBig,
  SquareChevronDown,
  SquareChevronLeft,
  SquareChevronRight,
  SquareChevronUp,
  SquareCode,
  SquareDashedBottom,
  SquareDashedBottomCode,
  SquareDashedKanban,
  SquareDashedMousePointer,
  SquareDivide,
  SquareDot,
  SquareEqual,
  SquareFunction,
  SquareGanttChart,
  SquareKanban,
  SquareLibrary,
  SquareM,
  SquareMenu,
  SquareMinus,
  SquareMousePointer,
  SquareParking,
  SquareParkingOff,
  SquarePen,
  SquarePercent,
  SquarePi,
  SquarePilcrow,
  SquarePlay,
  SquarePlus,
  SquarePower,
  SquareRadical,
  SquareScissors,
  SquareSigma,
  SquareSlash,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareStack,
  SquareTerminal,
  SquareUser,
  SquareUserRound,
  SquareX,
  Squircle,
  Squirrel,
  Stamp,
  Star,
  StarHalf,
  StarOff,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  Store,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  SunSnow,
  Sunrise,
  Sunset,
  Superscript,
  SwatchBook,
  SwissFranc,
  SwitchCamera,
  Sword,
  Swords,
  Syringe,
  Table,
  Table2,
  TableCellsMerge,
  TableCellsSplit,
  TableColumnsSplit,
  TableProperties,
  TableRowsSplit,
  Tablet,
  TabletSmartphone,
  Tablets,
  Tag,
  Tags,
  Tally1,
  Tally2,
  Tally3,
  Tally4,
  Tally5,
  Tangent,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  TestTube,
  TestTubeDiagonal,
  TestTubes,
  Text,
  TextCursor,
  TextCursorInput,
  TextQuote,
  TextSearch,
  TextSelect,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketMinus,
  TicketPercent,
  TicketPlus,
  TicketSlash,
  TicketX,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Tornado,
  Torus,
  Touchpad,
  TouchpadOff,
  TowerControl,
  ToyBrick,
  Tractor,
  TrafficCone,
  TrainFront,
  TrainFrontTunnel,
  TrainTrack,
  TramFront,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  TriangleAlert,
  TriangleRight,
  Trophy,
  Truck,
  Turtle,
  Tv,
  TvMinimal,
  TvMinimalPlay,
  Twitch,
  Twitter,
  Type,
  TypeOutline,
  Umbrella,
  UmbrellaOff,
  Underline,
  Undo,
  Undo2,
  UndoDot,
  UnfoldHorizontal,
  UnfoldVertical,
  Ungroup,
  University,
  Unlink,
  Unlink2,
  Unplug,
  Upload,
  Usb,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPen,
  UserPlus,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  UserRoundMinus,
  UserRoundPen,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UserSearch,
  UserX,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  UtilityPole,
  Variable,
  Vault,
  Vegan,
  VenetianMask,
  Vibrate,
  VibrateOff,
  Video,
  VideoOff,
  Videotape,
  View,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Vote,
  Wallet,
  WalletCards,
  WalletMinimal,
  Wallpaper,
  Wand,
  WandSparkles,
  Warehouse,
  WashingMachine,
  Watch,
  Waves,
  Waypoints,
  Webcam,
  Webhook,
  WebhookOff,
  Weight,
  Wheat,
  WheatOff,
  WholeWord,
  Wifi,
  WifiHigh,
  WifiLow,
  WifiOff,
  WifiZero,
  Wind,
  Wine,
  WineOff,
  Workflow,
  Worm,
  WrapText,
  Wrench,
  X,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const icons = [
  { name: "AArrowDown", component: AArrowDown },
  { name: "AArrowUp", component: AArrowUp },
  { name: "ALargeSmall", component: ALargeSmall },
  { name: "Accessibility", component: Accessibility },
  { name: "Activity", component: Activity },
  { name: "AirVent", component: AirVent },
  { name: "Airplay", component: Airplay },
  { name: "AlarmClock", component: AlarmClock },
  { name: "AlarmClockCheck", component: AlarmClockCheck },
  { name: "AlarmClockMinus", component: AlarmClockMinus },
  { name: "AlarmClockOff", component: AlarmClockOff },
  { name: "AlarmClockPlus", component: AlarmClockPlus },
  { name: "AlarmSmoke", component: AlarmSmoke },
  { name: "Album", component: Album },
  { name: "AlignCenter", component: AlignCenter },
  { name: "AlignCenterHorizontal", component: AlignCenterHorizontal },
  { name: "AlignCenterVertical", component: AlignCenterVertical },
  { name: "AlignEndHorizontal", component: AlignEndHorizontal },
  { name: "AlignEndVertical", component: AlignEndVertical },
  {
    name: "AlignHorizontalDistributeCenter",
    component: AlignHorizontalDistributeCenter,
  },
  {
    name: "AlignHorizontalDistributeEnd",
    component: AlignHorizontalDistributeEnd,
  },
  {
    name: "AlignHorizontalDistributeStart",
    component: AlignHorizontalDistributeStart,
  },
  {
    name: "AlignHorizontalJustifyCenter",
    component: AlignHorizontalJustifyCenter,
  },
  { name: "AlignHorizontalJustifyEnd", component: AlignHorizontalJustifyEnd },
  {
    name: "AlignHorizontalJustifyStart",
    component: AlignHorizontalJustifyStart,
  },
  {
    name: "AlignHorizontalSpaceAround",
    component: AlignHorizontalSpaceAround,
  },
  {
    name: "AlignHorizontalSpaceBetween",
    component: AlignHorizontalSpaceBetween,
  },
  { name: "AlignJustify", component: AlignJustify },
  { name: "AlignLeft", component: AlignLeft },
  { name: "AlignRight", component: AlignRight },
  { name: "AlignStartHorizontal", component: AlignStartHorizontal },
  { name: "AlignStartVertical", component: AlignStartVertical },
  {
    name: "AlignVerticalDistributeCenter",
    component: AlignVerticalDistributeCenter,
  },
  {
    name: "AlignVerticalDistributeEnd",
    component: AlignVerticalDistributeEnd,
  },
  {
    name: "AlignVerticalDistributeStart",
    component: AlignVerticalDistributeStart,
  },
  {
    name: "AlignVerticalJustifyCenter",
    component: AlignVerticalJustifyCenter,
  },
  { name: "AlignVerticalJustifyEnd", component: AlignVerticalJustifyEnd },
  { name: "AlignVerticalJustifyStart", component: AlignVerticalJustifyStart },
  { name: "AlignVerticalSpaceAround", component: AlignVerticalSpaceAround },
  { name: "AlignVerticalSpaceBetween", component: AlignVerticalSpaceBetween },
  { name: "Ambulance", component: Ambulance },
  { name: "Ampersand", component: Ampersand },
  { name: "Ampersands", component: Ampersands },
  { name: "Anchor", component: Anchor },
  { name: "Angry", component: Angry },
  { name: "Annoyed", component: Annoyed },
  { name: "Antenna", component: Antenna },
  { name: "Anvil", component: Anvil },
  { name: "Aperture", component: Aperture },
  { name: "AppWindow", component: AppWindow },
  { name: "AppWindowMac", component: AppWindowMac },
  { name: "Apple", component: Apple },
  { name: "Archive", component: Archive },
  { name: "ArchiveRestore", component: ArchiveRestore },
  { name: "ArchiveX", component: ArchiveX },
  { name: "AreaChart", component: AreaChart },
  { name: "Armchair", component: Armchair },
  { name: "ArrowBigDown", component: ArrowBigDown },
  { name: "ArrowBigDownDash", component: ArrowBigDownDash },
  { name: "ArrowBigLeft", component: ArrowBigLeft },
  { name: "ArrowBigLeftDash", component: ArrowBigLeftDash },
  { name: "ArrowBigRight", component: ArrowBigRight },
  { name: "ArrowBigRightDash", component: ArrowBigRightDash },
  { name: "ArrowBigUp", component: ArrowBigUp },
  { name: "ArrowBigUpDash", component: ArrowBigUpDash },
  { name: "ArrowDown", component: ArrowDown },
  { name: "ArrowDown01", component: ArrowDown01 },
  { name: "ArrowDown10", component: ArrowDown10 },
  { name: "ArrowDownAZ", component: ArrowDownAZ },
  { name: "ArrowDownFromLine", component: ArrowDownFromLine },
  { name: "ArrowDownLeft", component: ArrowDownLeft },
  { name: "ArrowDownNarrowWide", component: ArrowDownNarrowWide },
  { name: "ArrowDownRight", component: ArrowDownRight },
  { name: "ArrowDownToDot", component: ArrowDownToDot },
  { name: "ArrowDownToLine", component: ArrowDownToLine },
  { name: "ArrowDownUp", component: ArrowDownUp },
  { name: "ArrowDownWideNarrow", component: ArrowDownWideNarrow },
  { name: "ArrowDownZA", component: ArrowDownZA },
  { name: "ArrowLeft", component: ArrowLeft },
  { name: "ArrowLeftFromLine", component: ArrowLeftFromLine },
  { name: "ArrowLeftRight", component: ArrowLeftRight },
  { name: "ArrowLeftToLine", component: ArrowLeftToLine },
  { name: "ArrowRight", component: ArrowRight },
  { name: "ArrowRightFromLine", component: ArrowRightFromLine },
  { name: "ArrowRightLeft", component: ArrowRightLeft },
  { name: "ArrowRightToLine", component: ArrowRightToLine },
  { name: "ArrowUp", component: ArrowUp },
  { name: "ArrowUp01", component: ArrowUp01 },
  { name: "ArrowUp10", component: ArrowUp10 },
  { name: "ArrowUpAZ", component: ArrowUpAZ },
  { name: "ArrowUpDown", component: ArrowUpDown },
  { name: "ArrowUpFromDot", component: ArrowUpFromDot },
  { name: "ArrowUpFromLine", component: ArrowUpFromLine },
  { name: "ArrowUpLeft", component: ArrowUpLeft },
  { name: "ArrowUpNarrowWide", component: ArrowUpNarrowWide },
  { name: "ArrowUpRight", component: ArrowUpRight },
  { name: "ArrowUpToLine", component: ArrowUpToLine },
  { name: "ArrowUpWideNarrow", component: ArrowUpWideNarrow },
  { name: "ArrowUpZA", component: ArrowUpZA },
  { name: "ArrowsUpFromLine", component: ArrowsUpFromLine },
  { name: "Asterisk", component: Asterisk },
  { name: "AtSign", component: AtSign },
  { name: "Atom", component: Atom },
  { name: "AudioLines", component: AudioLines },
  { name: "AudioWaveform", component: AudioWaveform },
  { name: "Award", component: Award },
  { name: "Axe", component: Axe },
  { name: "Axis3d", component: Axis3d },
  { name: "Baby", component: Baby },
  { name: "Backpack", component: Backpack },
  { name: "Badge", component: Badge },
  { name: "BadgeAlert", component: BadgeAlert },
  { name: "BadgeCent", component: BadgeCent },
  { name: "BadgeCheck", component: BadgeCheck },
  { name: "BadgeDollarSign", component: BadgeDollarSign },
  { name: "BadgeEuro", component: BadgeEuro },
  { name: "BadgeHelp", component: BadgeHelp },
  { name: "BadgeIndianRupee", component: BadgeIndianRupee },
  { name: "BadgeInfo", component: BadgeInfo },
  { name: "BadgeJapaneseYen", component: BadgeJapaneseYen },
  { name: "BadgeMinus", component: BadgeMinus },
  { name: "BadgePercent", component: BadgePercent },
  { name: "BadgePlus", component: BadgePlus },
  { name: "BadgePoundSterling", component: BadgePoundSterling },
  { name: "BadgeRussianRuble", component: BadgeRussianRuble },
  { name: "BadgeSwissFranc", component: BadgeSwissFranc },
  { name: "BadgeX", component: BadgeX },
  { name: "BaggageClaim", component: BaggageClaim },
  { name: "Ban", component: Ban },
  { name: "Banana", component: Banana },
  { name: "Banknote", component: Banknote },
  { name: "BarChart", component: BarChart },
  { name: "BarChart2", component: BarChart2 },
  { name: "BarChart3", component: BarChart3 },
  { name: "BarChart4", component: BarChart4 },
  { name: "BarChartBig", component: BarChartBig },
  { name: "BarChartHorizontal", component: BarChartHorizontal },
  { name: "BarChartHorizontalBig", component: BarChartHorizontalBig },
  { name: "Barcode", component: Barcode },
  { name: "Baseline", component: Baseline },
  { name: "Bath", component: Bath },
  { name: "Battery", component: Battery },
  { name: "BatteryCharging", component: BatteryCharging },
  { name: "BatteryFull", component: BatteryFull },
  { name: "BatteryLow", component: BatteryLow },
  { name: "BatteryMedium", component: BatteryMedium },
  { name: "BatteryWarning", component: BatteryWarning },
  { name: "Beaker", component: Beaker },
  { name: "Bean", component: Bean },
  { name: "BeanOff", component: BeanOff },
  { name: "Bed", component: Bed },
  { name: "BedDouble", component: BedDouble },
  { name: "BedSingle", component: BedSingle },
  { name: "Beef", component: Beef },
  { name: "Beer", component: Beer },
  { name: "BeerOff", component: BeerOff },
  { name: "Bell", component: Bell },
  { name: "BellDot", component: BellDot },
  { name: "BellElectric", component: BellElectric },
  { name: "BellMinus", component: BellMinus },
  { name: "BellOff", component: BellOff },
  { name: "BellPlus", component: BellPlus },
  { name: "BellRing", component: BellRing },
  { name: "BetweenHorizontalEnd", component: BetweenHorizontalEnd },
  { name: "BetweenHorizontalStart", component: BetweenHorizontalStart },
  { name: "BetweenVerticalEnd", component: BetweenVerticalEnd },
  { name: "BetweenVerticalStart", component: BetweenVerticalStart },
  { name: "BicepsFlexed", component: BicepsFlexed },
  { name: "Bike", component: Bike },
  { name: "Binary", component: Binary },
  { name: "Biohazard", component: Biohazard },
  { name: "Bird", component: Bird },
  { name: "Bitcoin", component: Bitcoin },
  { name: "Blend", component: Blend },
  { name: "Blinds", component: Blinds },
  { name: "Blocks", component: Blocks },
  { name: "Bluetooth", component: Bluetooth },
  { name: "BluetoothConnected", component: BluetoothConnected },
  { name: "BluetoothOff", component: BluetoothOff },
  { name: "BluetoothSearching", component: BluetoothSearching },
  { name: "Bold", component: Bold },
  { name: "Bolt", component: Bolt },
  { name: "Bomb", component: Bomb },
  { name: "Bone", component: Bone },
  { name: "Book", component: Book },
  { name: "BookA", component: BookA },
  { name: "BookAudio", component: BookAudio },
  { name: "BookCheck", component: BookCheck },
  { name: "BookCopy", component: BookCopy },
  { name: "BookDashed", component: BookDashed },
  { name: "BookDown", component: BookDown },
  { name: "BookHeadphones", component: BookHeadphones },
  { name: "BookHeart", component: BookHeart },
  { name: "BookImage", component: BookImage },
  { name: "BookKey", component: BookKey },
  { name: "BookLock", component: BookLock },
  { name: "BookMarked", component: BookMarked },
  { name: "BookMinus", component: BookMinus },
  { name: "BookOpen", component: BookOpen },
  { name: "BookOpenCheck", component: BookOpenCheck },
  { name: "BookOpenText", component: BookOpenText },
  { name: "BookPlus", component: BookPlus },
  { name: "BookText", component: BookText },
  { name: "BookType", component: BookType },
  { name: "BookUp", component: BookUp },
  { name: "BookUp2", component: BookUp2 },
  { name: "BookUser", component: BookUser },
  { name: "BookX", component: BookX },
  { name: "Bookmark", component: Bookmark },
  { name: "BookmarkCheck", component: BookmarkCheck },
  { name: "BookmarkMinus", component: BookmarkMinus },
  { name: "BookmarkPlus", component: BookmarkPlus },
  { name: "BookmarkX", component: BookmarkX },
  { name: "BoomBox", component: BoomBox },
  { name: "Bot", component: Bot },
  { name: "BotMessageSquare", component: BotMessageSquare },
  { name: "BotOff", component: BotOff },
  { name: "Box", component: Box },
  { name: "BoxSelect", component: BoxSelect },
  { name: "Boxes", component: Boxes },
  { name: "Braces", component: Braces },
  { name: "Brackets", component: Brackets },
  { name: "Brain", component: Brain },
  { name: "BrainCircuit", component: BrainCircuit },
  { name: "BrainCog", component: BrainCog },
  { name: "BrickWall", component: BrickWall },
  { name: "Briefcase", component: Briefcase },
  { name: "BriefcaseBusiness", component: BriefcaseBusiness },
  { name: "BriefcaseMedical", component: BriefcaseMedical },
  { name: "BringToFront", component: BringToFront },
  { name: "Brush", component: Brush },
  { name: "Bug", component: Bug },
  { name: "BugOff", component: BugOff },
  { name: "BugPlay", component: BugPlay },
  { name: "Building", component: Building },
  { name: "Building2", component: Building2 },
  { name: "Bus", component: Bus },
  { name: "BusFront", component: BusFront },
  { name: "Cable", component: Cable },
  { name: "CableCar", component: CableCar },
  { name: "Cake", component: Cake },
  { name: "CakeSlice", component: CakeSlice },
  { name: "Calculator", component: Calculator },
  { name: "Calendar", component: Calendar },
  { name: "CalendarArrowDown", component: CalendarArrowDown },
  { name: "CalendarArrowUp", component: CalendarArrowUp },
  { name: "CalendarCheck", component: CalendarCheck },
  { name: "CalendarCheck2", component: CalendarCheck2 },
  { name: "CalendarClock", component: CalendarClock },
  { name: "CalendarCog", component: CalendarCog },
  { name: "CalendarDays", component: CalendarDays },
  { name: "CalendarFold", component: CalendarFold },
  { name: "CalendarHeart", component: CalendarHeart },
  { name: "CalendarMinus", component: CalendarMinus },
  { name: "CalendarMinus2", component: CalendarMinus2 },
  { name: "CalendarOff", component: CalendarOff },
  { name: "CalendarPlus", component: CalendarPlus },
  { name: "CalendarPlus2", component: CalendarPlus2 },
  { name: "CalendarRange", component: CalendarRange },
  { name: "CalendarSearch", component: CalendarSearch },
  { name: "CalendarX", component: CalendarX },
  { name: "CalendarX2", component: CalendarX2 },
  { name: "Camera", component: Camera },
  { name: "CameraOff", component: CameraOff },
  { name: "CandlestickChart", component: CandlestickChart },
  { name: "Candy", component: Candy },
  { name: "CandyCane", component: CandyCane },
  { name: "CandyOff", component: CandyOff },
  { name: "Cannabis", component: Cannabis },
  { name: "Captions", component: Captions },
  { name: "CaptionsOff", component: CaptionsOff },
  { name: "Car", component: Car },
  { name: "CarFront", component: CarFront },
  { name: "CarTaxiFront", component: CarTaxiFront },
  { name: "Caravan", component: Caravan },
  { name: "Carrot", component: Carrot },
  { name: "CaseLower", component: CaseLower },
  { name: "CaseSensitive", component: CaseSensitive },
  { name: "CaseUpper", component: CaseUpper },
  { name: "CassetteTape", component: CassetteTape },
  { name: "Cast", component: Cast },
  { name: "Castle", component: Castle },
  { name: "Cat", component: Cat },
  { name: "Cctv", component: Cctv },
  { name: "Check", component: Check },
  { name: "CheckCheck", component: CheckCheck },
  { name: "ChefHat", component: ChefHat },
  { name: "Cherry", component: Cherry },
  { name: "ChevronDown", component: ChevronDown },
  { name: "ChevronFirst", component: ChevronFirst },
  { name: "ChevronLast", component: ChevronLast },
  { name: "ChevronLeft", component: ChevronLeft },
  { name: "ChevronRight", component: ChevronRight },
  { name: "ChevronUp", component: ChevronUp },
  { name: "ChevronsDown", component: ChevronsDown },
  { name: "ChevronsDownUp", component: ChevronsDownUp },
  { name: "ChevronsLeft", component: ChevronsLeft },
  { name: "ChevronsLeftRight", component: ChevronsLeftRight },
  { name: "ChevronsRight", component: ChevronsRight },
  { name: "ChevronsRightLeft", component: ChevronsRightLeft },
  { name: "ChevronsUp", component: ChevronsUp },
  { name: "ChevronsUpDown", component: ChevronsUpDown },
  { name: "Chrome", component: Chrome },
  { name: "Church", component: Church },
  { name: "Cigarette", component: Cigarette },
  { name: "CigaretteOff", component: CigaretteOff },
  { name: "Circle", component: Circle },
  { name: "CircleAlert", component: CircleAlert },
  { name: "CircleArrowDown", component: CircleArrowDown },
  { name: "CircleArrowLeft", component: CircleArrowLeft },
  { name: "CircleArrowOutDownLeft", component: CircleArrowOutDownLeft },
  { name: "CircleArrowOutDownRight", component: CircleArrowOutDownRight },
  { name: "CircleArrowOutUpLeft", component: CircleArrowOutUpLeft },
  { name: "CircleArrowOutUpRight", component: CircleArrowOutUpRight },
  { name: "CircleArrowRight", component: CircleArrowRight },
  { name: "CircleArrowUp", component: CircleArrowUp },
  { name: "CircleCheck", component: CircleCheck },
  { name: "CircleCheckBig", component: CircleCheckBig },
  { name: "CircleChevronDown", component: CircleChevronDown },
  { name: "CircleChevronLeft", component: CircleChevronLeft },
  { name: "CircleChevronRight", component: CircleChevronRight },
  { name: "CircleChevronUp", component: CircleChevronUp },
  { name: "CircleDashed", component: CircleDashed },
  { name: "CircleDivide", component: CircleDivide },
  { name: "CircleDollarSign", component: CircleDollarSign },
  { name: "CircleDot", component: CircleDot },
  { name: "CircleDotDashed", component: CircleDotDashed },
  { name: "CircleEllipsis", component: CircleEllipsis },
  { name: "CircleEqual", component: CircleEqual },
  { name: "CircleFadingPlus", component: CircleFadingPlus },
  { name: "CircleGauge", component: CircleGauge },
  { name: "CircleHelp", component: CircleHelp },
  { name: "CircleMinus", component: CircleMinus },
  { name: "CircleOff", component: CircleOff },
  { name: "CircleParking", component: CircleParking },
  { name: "CircleParkingOff", component: CircleParkingOff },
  { name: "CirclePause", component: CirclePause },
  { name: "CirclePercent", component: CirclePercent },
  { name: "CirclePlay", component: CirclePlay },
  { name: "CirclePlus", component: CirclePlus },
  { name: "CirclePower", component: CirclePower },
  { name: "CircleSlash", component: CircleSlash },
  { name: "CircleSlash2", component: CircleSlash2 },
  { name: "CircleStop", component: CircleStop },
  { name: "CircleUser", component: CircleUser },
  { name: "CircleUserRound", component: CircleUserRound },
  { name: "CircleX", component: CircleX },
  { name: "CircuitBoard", component: CircuitBoard },
  { name: "Citrus", component: Citrus },
  { name: "Clapperboard", component: Clapperboard },
  { name: "Clipboard", component: Clipboard },
  { name: "ClipboardCheck", component: ClipboardCheck },
  { name: "ClipboardCopy", component: ClipboardCopy },
  { name: "ClipboardList", component: ClipboardList },
  { name: "ClipboardMinus", component: ClipboardMinus },
  { name: "ClipboardPaste", component: ClipboardPaste },
  { name: "ClipboardPen", component: ClipboardPen },
  { name: "ClipboardPenLine", component: ClipboardPenLine },
  { name: "ClipboardPlus", component: ClipboardPlus },
  { name: "ClipboardType", component: ClipboardType },
  { name: "ClipboardX", component: ClipboardX },
  { name: "Clock", component: Clock },
  { name: "Clock1", component: Clock1 },
  { name: "Clock10", component: Clock10 },
  { name: "Clock11", component: Clock11 },
  { name: "Clock12", component: Clock12 },
  { name: "Clock2", component: Clock2 },
  { name: "Clock3", component: Clock3 },
  { name: "Clock4", component: Clock4 },
  { name: "Clock5", component: Clock5 },
  { name: "Clock6", component: Clock6 },
  { name: "Clock7", component: Clock7 },
  { name: "Clock8", component: Clock8 },
  { name: "Clock9", component: Clock9 },
  { name: "ClockArrowDown", component: ClockArrowDown },
  { name: "ClockArrowUp", component: ClockArrowUp },
  { name: "Cloud", component: Cloud },
  { name: "CloudCog", component: CloudCog },
  { name: "CloudDownload", component: CloudDownload },
  { name: "CloudDrizzle", component: CloudDrizzle },
  { name: "CloudFog", component: CloudFog },
  { name: "CloudHail", component: CloudHail },
  { name: "CloudLightning", component: CloudLightning },
  { name: "CloudMoon", component: CloudMoon },
  { name: "CloudMoonRain", component: CloudMoonRain },
  { name: "CloudOff", component: CloudOff },
  { name: "CloudRain", component: CloudRain },
  { name: "CloudRainWind", component: CloudRainWind },
  { name: "CloudSnow", component: CloudSnow },
  { name: "CloudSun", component: CloudSun },
  { name: "CloudSunRain", component: CloudSunRain },
  { name: "CloudUpload", component: CloudUpload },
  { name: "Cloudy", component: Cloudy },
  { name: "Clover", component: Clover },
  { name: "Club", component: Club },
  { name: "Code", component: Code },
  { name: "CodeXml", component: CodeXml },
  { name: "Codepen", component: Codepen },
  { name: "Codesandbox", component: Codesandbox },
  { name: "Coffee", component: Coffee },
  { name: "Cog", component: Cog },
  { name: "Coins", component: Coins },
  { name: "Columns2", component: Columns2 },
  { name: "Columns3", component: Columns3 },
  { name: "Columns4", component: Columns4 },
  { name: "Combine", component: Combine },
  { name: "Command", component: Command },
  { name: "Compass", component: Compass },
  { name: "Component", component: Component },
  { name: "Computer", component: Computer },
  { name: "ConciergeBell", component: ConciergeBell },
  { name: "Cone", component: Cone },
  { name: "Construction", component: Construction },
  { name: "Contact", component: Contact },
  { name: "ContactRound", component: ContactRound },
  { name: "Container", component: Container },
  { name: "Contrast", component: Contrast },
  { name: "Cookie", component: Cookie },
  { name: "CookingPot", component: CookingPot },
  { name: "Copy", component: Copy },
  { name: "CopyCheck", component: CopyCheck },
  { name: "CopyMinus", component: CopyMinus },
  { name: "CopyPlus", component: CopyPlus },
  { name: "CopySlash", component: CopySlash },
  { name: "CopyX", component: CopyX },
  { name: "Copyleft", component: Copyleft },
  { name: "Copyright", component: Copyright },
  { name: "CornerDownLeft", component: CornerDownLeft },
  { name: "CornerDownRight", component: CornerDownRight },
  { name: "CornerLeftDown", component: CornerLeftDown },
  { name: "CornerLeftUp", component: CornerLeftUp },
  { name: "CornerRightDown", component: CornerRightDown },
  { name: "CornerRightUp", component: CornerRightUp },
  { name: "CornerUpLeft", component: CornerUpLeft },
  { name: "CornerUpRight", component: CornerUpRight },
  { name: "Cpu", component: Cpu },
  { name: "CreativeCommons", component: CreativeCommons },
  { name: "CreditCard", component: CreditCard },
  { name: "Croissant", component: Croissant },
  { name: "Crop", component: Crop },
  { name: "Cross", component: Cross },
  { name: "Crosshair", component: Crosshair },
  { name: "Crown", component: Crown },
  { name: "Cuboid", component: Cuboid },
  { name: "CupSoda", component: CupSoda },
  { name: "Currency", component: Currency },
  { name: "Cylinder", component: Cylinder },
  { name: "Database", component: Database },
  { name: "DatabaseBackup", component: DatabaseBackup },
  { name: "DatabaseZap", component: DatabaseZap },
  { name: "Delete", component: Delete },
  { name: "Dessert", component: Dessert },
  { name: "Diameter", component: Diameter },
  { name: "Diamond", component: Diamond },
  { name: "DiamondMinus", component: DiamondMinus },
  { name: "DiamondPercent", component: DiamondPercent },
  { name: "DiamondPlus", component: DiamondPlus },
  { name: "Dice1", component: Dice1 },
  { name: "Dice2", component: Dice2 },
  { name: "Dice3", component: Dice3 },
  { name: "Dice4", component: Dice4 },
  { name: "Dice5", component: Dice5 },
  { name: "Dice6", component: Dice6 },
  { name: "Dices", component: Dices },
  { name: "Diff", component: Diff },
  { name: "Disc", component: Disc },
  { name: "Disc2", component: Disc2 },
  { name: "Disc3", component: Disc3 },
  { name: "DiscAlbum", component: DiscAlbum },
  { name: "Divide", component: Divide },
  { name: "Dna", component: Dna },
  { name: "DnaOff", component: DnaOff },
  { name: "Dock", component: Dock },
  { name: "Dog", component: Dog },
  { name: "DollarSign", component: DollarSign },
  { name: "Donut", component: Donut },
  { name: "DoorClosed", component: DoorClosed },
  { name: "DoorOpen", component: DoorOpen },
  { name: "Dot", component: Dot },
  { name: "Download", component: Download },
  { name: "DraftingCompass", component: DraftingCompass },
  { name: "Drama", component: Drama },
  { name: "Dribbble", component: Dribbble },
  { name: "Drill", component: Drill },
  { name: "Droplet", component: Droplet },
  { name: "Droplets", component: Droplets },
  { name: "Drum", component: Drum },
  { name: "Drumstick", component: Drumstick },
  { name: "Dumbbell", component: Dumbbell },
  { name: "Ear", component: Ear },
  { name: "EarOff", component: EarOff },
  { name: "Earth", component: Earth },
  { name: "EarthLock", component: EarthLock },
  { name: "Eclipse", component: Eclipse },
  { name: "Egg", component: Egg },
  { name: "EggFried", component: EggFried },
  { name: "EggOff", component: EggOff },
  { name: "Ellipsis", component: Ellipsis },
  { name: "EllipsisVertical", component: EllipsisVertical },
  { name: "Equal", component: Equal },
  { name: "EqualNot", component: EqualNot },
  { name: "Eraser", component: Eraser },
  { name: "Euro", component: Euro },
  { name: "Expand", component: Expand },
  { name: "ExternalLink", component: ExternalLink },
  { name: "Eye", component: Eye },
  { name: "EyeOff", component: EyeOff },
  { name: "Facebook", component: Facebook },
  { name: "Factory", component: Factory },
  { name: "Fan", component: Fan },
  { name: "FastForward", component: FastForward },
  { name: "Feather", component: Feather },
  { name: "Fence", component: Fence },
  { name: "FerrisWheel", component: FerrisWheel },
  { name: "Figma", component: Figma },
  { name: "File", component: File },
  { name: "FileArchive", component: FileArchive },
  { name: "FileAudio", component: FileAudio },
  { name: "FileAudio2", component: FileAudio2 },
  { name: "FileAxis3d", component: FileAxis3d },
  { name: "FileBadge", component: FileBadge },
  { name: "FileBadge2", component: FileBadge2 },
  { name: "FileBarChart", component: FileBarChart },
  { name: "FileBarChart2", component: FileBarChart2 },
  { name: "FileBox", component: FileBox },
  { name: "FileCheck", component: FileCheck },
  { name: "FileCheck2", component: FileCheck2 },
  { name: "FileClock", component: FileClock },
  { name: "FileCode", component: FileCode },
  { name: "FileCode2", component: FileCode2 },
  { name: "FileCog", component: FileCog },
  { name: "FileDiff", component: FileDiff },
  { name: "FileDigit", component: FileDigit },
  { name: "FileDown", component: FileDown },
  { name: "FileHeart", component: FileHeart },
  { name: "FileImage", component: FileImage },
  { name: "FileInput", component: FileInput },
  { name: "FileJson", component: FileJson },
  { name: "FileJson2", component: FileJson2 },
  { name: "FileKey", component: FileKey },
  { name: "FileKey2", component: FileKey2 },
  { name: "FileLineChart", component: FileLineChart },
  { name: "FileLock", component: FileLock },
  { name: "FileLock2", component: FileLock2 },
  { name: "FileMinus", component: FileMinus },
  { name: "FileMinus2", component: FileMinus2 },
  { name: "FileMusic", component: FileMusic },
  { name: "FileOutput", component: FileOutput },
  { name: "FilePen", component: FilePen },
  { name: "FilePenLine", component: FilePenLine },
  { name: "FilePieChart", component: FilePieChart },
  { name: "FilePlus", component: FilePlus },
  { name: "FilePlus2", component: FilePlus2 },
  { name: "FileQuestion", component: FileQuestion },
  { name: "FileScan", component: FileScan },
  { name: "FileSearch", component: FileSearch },
  { name: "FileSearch2", component: FileSearch2 },
  { name: "FileSliders", component: FileSliders },
  { name: "FileSpreadsheet", component: FileSpreadsheet },
  { name: "FileStack", component: FileStack },
  { name: "FileSymlink", component: FileSymlink },
  { name: "FileTerminal", component: FileTerminal },
  { name: "FileText", component: FileText },
  { name: "FileType", component: FileType },
  { name: "FileType2", component: FileType2 },
  { name: "FileUp", component: FileUp },
  { name: "FileVideo", component: FileVideo },
  { name: "FileVideo2", component: FileVideo2 },
  { name: "FileVolume", component: FileVolume },
  { name: "FileVolume2", component: FileVolume2 },
  { name: "FileWarning", component: FileWarning },
  { name: "FileX", component: FileX },
  { name: "FileX2", component: FileX2 },
  { name: "Files", component: Files },
  { name: "Film", component: Film },
  { name: "Filter", component: Filter },
  { name: "FilterX", component: FilterX },
  { name: "Fingerprint", component: Fingerprint },
  { name: "FireExtinguisher", component: FireExtinguisher },
  { name: "Fish", component: Fish },
  { name: "FishOff", component: FishOff },
  { name: "FishSymbol", component: FishSymbol },
  { name: "Flag", component: Flag },
  { name: "FlagOff", component: FlagOff },
  { name: "FlagTriangleLeft", component: FlagTriangleLeft },
  { name: "FlagTriangleRight", component: FlagTriangleRight },
  { name: "Flame", component: Flame },
  { name: "FlameKindling", component: FlameKindling },
  { name: "Flashlight", component: Flashlight },
  { name: "FlashlightOff", component: FlashlightOff },
  { name: "FlaskConical", component: FlaskConical },
  { name: "FlaskConicalOff", component: FlaskConicalOff },
  { name: "FlaskRound", component: FlaskRound },
  { name: "FlipHorizontal", component: FlipHorizontal },
  { name: "FlipHorizontal2", component: FlipHorizontal2 },
  { name: "FlipVertical", component: FlipVertical },
  { name: "FlipVertical2", component: FlipVertical2 },
  { name: "Flower", component: Flower },
  { name: "Flower2", component: Flower2 },
  { name: "Focus", component: Focus },
  { name: "FoldHorizontal", component: FoldHorizontal },
  { name: "FoldVertical", component: FoldVertical },
  { name: "Folder", component: Folder },
  { name: "FolderArchive", component: FolderArchive },
  { name: "FolderCheck", component: FolderCheck },
  { name: "FolderClock", component: FolderClock },
  { name: "FolderClosed", component: FolderClosed },
  { name: "FolderCode", component: FolderCode },
  { name: "FolderCog", component: FolderCog },
  { name: "FolderDot", component: FolderDot },
  { name: "FolderDown", component: FolderDown },
  { name: "FolderGit", component: FolderGit },
  { name: "FolderGit2", component: FolderGit2 },
  { name: "FolderHeart", component: FolderHeart },
  { name: "FolderInput", component: FolderInput },
  { name: "FolderKanban", component: FolderKanban },
  { name: "FolderKey", component: FolderKey },
  { name: "FolderLock", component: FolderLock },
  { name: "FolderMinus", component: FolderMinus },
  { name: "FolderOpen", component: FolderOpen },
  { name: "FolderOpenDot", component: FolderOpenDot },
  { name: "FolderOutput", component: FolderOutput },
  { name: "FolderPen", component: FolderPen },
  { name: "FolderPlus", component: FolderPlus },
  { name: "FolderRoot", component: FolderRoot },
  { name: "FolderSearch", component: FolderSearch },
  { name: "FolderSearch2", component: FolderSearch2 },
  { name: "FolderSymlink", component: FolderSymlink },
  { name: "FolderSync", component: FolderSync },
  { name: "FolderTree", component: FolderTree },
  { name: "FolderUp", component: FolderUp },
  { name: "FolderX", component: FolderX },
  { name: "Folders", component: Folders },
  { name: "Footprints", component: Footprints },
  { name: "Forklift", component: Forklift },
  { name: "Forward", component: Forward },
  { name: "Frame", component: Frame },
  { name: "Framer", component: Framer },
  { name: "Frown", component: Frown },
  { name: "Fuel", component: Fuel },
  { name: "Fullscreen", component: Fullscreen },
  { name: "GalleryHorizontal", component: GalleryHorizontal },
  { name: "GalleryHorizontalEnd", component: GalleryHorizontalEnd },
  { name: "GalleryThumbnails", component: GalleryThumbnails },
  { name: "GalleryVertical", component: GalleryVertical },
  { name: "GalleryVerticalEnd", component: GalleryVerticalEnd },
  { name: "Gamepad", component: Gamepad },
  { name: "Gamepad2", component: Gamepad2 },
  { name: "GanttChart", component: GanttChart },
  { name: "Gauge", component: Gauge },
  { name: "Gavel", component: Gavel },
  { name: "Gem", component: Gem },
  { name: "Ghost", component: Ghost },
  { name: "Gift", component: Gift },
  { name: "GitBranch", component: GitBranch },
  { name: "GitBranchPlus", component: GitBranchPlus },
  { name: "GitCommitHorizontal", component: GitCommitHorizontal },
  { name: "GitCommitVertical", component: GitCommitVertical },
  { name: "GitCompare", component: GitCompare },
  { name: "GitCompareArrows", component: GitCompareArrows },
  { name: "GitFork", component: GitFork },
  { name: "GitGraph", component: GitGraph },
  { name: "GitMerge", component: GitMerge },
  { name: "GitPullRequest", component: GitPullRequest },
  { name: "GitPullRequestArrow", component: GitPullRequestArrow },
  { name: "GitPullRequestClosed", component: GitPullRequestClosed },
  { name: "GitPullRequestCreate", component: GitPullRequestCreate },
  { name: "GitPullRequestCreateArrow", component: GitPullRequestCreateArrow },
  { name: "GitPullRequestDraft", component: GitPullRequestDraft },
  { name: "Github", component: Github },
  { name: "Gitlab", component: Gitlab },
  { name: "GlassWater", component: GlassWater },
  { name: "Glasses", component: Glasses },
  { name: "Globe", component: Globe },
  { name: "GlobeLock", component: GlobeLock },
  { name: "Goal", component: Goal },
  { name: "Grab", component: Grab },
  { name: "GraduationCap", component: GraduationCap },
  { name: "Grape", component: Grape },
  { name: "Grid2x2", component: Grid2x2 },
  { name: "Grid2x2Check", component: Grid2x2Check },
  { name: "Grid2x2X", component: Grid2x2X },
  { name: "Grid3x3", component: Grid3x3 },
  { name: "Grip", component: Grip },
  { name: "GripHorizontal", component: GripHorizontal },
  { name: "GripVertical", component: GripVertical },
  { name: "Group", component: Group },
  { name: "Guitar", component: Guitar },
  { name: "Ham", component: Ham },
  { name: "Hammer", component: Hammer },
  { name: "Hand", component: Hand },
  { name: "HandCoins", component: HandCoins },
  { name: "HandHeart", component: HandHeart },
  { name: "HandHelping", component: HandHelping },
  { name: "HandMetal", component: HandMetal },
  { name: "HandPlatter", component: HandPlatter },
  { name: "Handshake", component: Handshake },
  { name: "HardDrive", component: HardDrive },
  { name: "HardDriveDownload", component: HardDriveDownload },
  { name: "HardDriveUpload", component: HardDriveUpload },
  { name: "HardHat", component: HardHat },
  { name: "Hash", component: Hash },
  { name: "Haze", component: Haze },
  { name: "HdmiPort", component: HdmiPort },
  { name: "Heading", component: Heading },
  { name: "Heading1", component: Heading1 },
  { name: "Heading2", component: Heading2 },
  { name: "Heading3", component: Heading3 },
  { name: "Heading4", component: Heading4 },
  { name: "Heading5", component: Heading5 },
  { name: "Heading6", component: Heading6 },
  { name: "Headphones", component: Headphones },
  { name: "Headset", component: Headset },
  { name: "Heart", component: Heart },
  { name: "HeartCrack", component: HeartCrack },
  { name: "HeartHandshake", component: HeartHandshake },
  { name: "HeartOff", component: HeartOff },
  { name: "HeartPulse", component: HeartPulse },
  { name: "Heater", component: Heater },
  { name: "Hexagon", component: Hexagon },
  { name: "Highlighter", component: Highlighter },
  { name: "History", component: History },
  { name: "Hop", component: Hop },
  { name: "HopOff", component: HopOff },
  { name: "Hospital", component: Hospital },
  { name: "Hotel", component: Hotel },
  { name: "Hourglass", component: Hourglass },
  { name: "House", component: House },
  { name: "HousePlug", component: HousePlug },
  { name: "HousePlus", component: HousePlus },
  { name: "IceCreamBowl", component: IceCreamBowl },
  { name: "IceCreamCone", component: IceCreamCone },
  { name: "Image", component: Image },
  { name: "ImageDown", component: ImageDown },
  { name: "ImageMinus", component: ImageMinus },
  { name: "ImageOff", component: ImageOff },
  { name: "ImagePlay", component: ImagePlay },
  { name: "ImagePlus", component: ImagePlus },
  { name: "ImageUp", component: ImageUp },
  { name: "Images", component: Images },
  { name: "Import", component: Import },
  { name: "Inbox", component: Inbox },
  { name: "IndentDecrease", component: IndentDecrease },
  { name: "IndentIncrease", component: IndentIncrease },
  { name: "IndianRupee", component: IndianRupee },
  { name: "Infinity", component: Infinity },
  { name: "Info", component: Info },
  { name: "InspectionPanel", component: InspectionPanel },
  { name: "Instagram", component: Instagram },
  { name: "Italic", component: Italic },
  { name: "IterationCcw", component: IterationCcw },
  { name: "IterationCw", component: IterationCw },
  { name: "JapaneseYen", component: JapaneseYen },
  { name: "Joystick", component: Joystick },
  { name: "Kanban", component: Kanban },
  { name: "Key", component: Key },
  { name: "KeyRound", component: KeyRound },
  { name: "KeySquare", component: KeySquare },
  { name: "Keyboard", component: Keyboard },
  { name: "KeyboardMusic", component: KeyboardMusic },
  { name: "KeyboardOff", component: KeyboardOff },
  { name: "Lamp", component: Lamp },
  { name: "LampCeiling", component: LampCeiling },
  { name: "LampDesk", component: LampDesk },
  { name: "LampFloor", component: LampFloor },
  { name: "LampWallDown", component: LampWallDown },
  { name: "LampWallUp", component: LampWallUp },
  { name: "LandPlot", component: LandPlot },
  { name: "Landmark", component: Landmark },
  { name: "Languages", component: Languages },
  { name: "Laptop", component: Laptop },
  { name: "LaptopMinimal", component: LaptopMinimal },
  { name: "Lasso", component: Lasso },
  { name: "LassoSelect", component: LassoSelect },
  { name: "Laugh", component: Laugh },
  { name: "Layers", component: Layers },
  { name: "Layers2", component: Layers2 },
  { name: "Layers3", component: Layers3 },
  { name: "LayoutDashboard", component: LayoutDashboard },
  { name: "LayoutGrid", component: LayoutGrid },
  { name: "LayoutList", component: LayoutList },
  { name: "LayoutPanelLeft", component: LayoutPanelLeft },
  { name: "LayoutPanelTop", component: LayoutPanelTop },
  { name: "LayoutTemplate", component: LayoutTemplate },
  { name: "Leaf", component: Leaf },
  { name: "LeafyGreen", component: LeafyGreen },
  { name: "Lectern", component: Lectern },
  { name: "Library", component: Library },
  { name: "LibraryBig", component: LibraryBig },
  { name: "LifeBuoy", component: LifeBuoy },
  { name: "Ligature", component: Ligature },
  { name: "Lightbulb", component: Lightbulb },
  { name: "LightbulbOff", component: LightbulbOff },
  { name: "LineChart", component: LineChart },
  { name: "Link", component: Link },
  { name: "Link2", component: Link2 },
  { name: "Link2Off", component: Link2Off },
  { name: "Linkedin", component: Linkedin },
  { name: "List", component: List },
  { name: "ListCheck", component: ListCheck },
  { name: "ListChecks", component: ListChecks },
  { name: "ListCollapse", component: ListCollapse },
  { name: "ListEnd", component: ListEnd },
  { name: "ListFilter", component: ListFilter },
  { name: "ListMinus", component: ListMinus },
  { name: "ListMusic", component: ListMusic },
  { name: "ListOrdered", component: ListOrdered },
  { name: "ListPlus", component: ListPlus },
  { name: "ListRestart", component: ListRestart },
  { name: "ListStart", component: ListStart },
  { name: "ListTodo", component: ListTodo },
  { name: "ListTree", component: ListTree },
  { name: "ListVideo", component: ListVideo },
  { name: "ListX", component: ListX },
  { name: "Loader", component: Loader },
  { name: "LoaderCircle", component: LoaderCircle },
  { name: "LoaderPinwheel", component: LoaderPinwheel },
  { name: "Locate", component: Locate },
  { name: "LocateFixed", component: LocateFixed },
  { name: "LocateOff", component: LocateOff },
  { name: "Lock", component: Lock },
  { name: "LockKeyhole", component: LockKeyhole },
  { name: "LockKeyholeOpen", component: LockKeyholeOpen },
  { name: "LockOpen", component: LockOpen },
  { name: "LogIn", component: LogIn },
  { name: "LogOut", component: LogOut },
  { name: "Logs", component: Logs },
  { name: "Lollipop", component: Lollipop },
  { name: "Luggage", component: Luggage },
  { name: "Magnet", component: Magnet },
  { name: "Mail", component: Mail },
  { name: "MailCheck", component: MailCheck },
  { name: "MailMinus", component: MailMinus },
  { name: "MailOpen", component: MailOpen },
  { name: "MailPlus", component: MailPlus },
  { name: "MailQuestion", component: MailQuestion },
  { name: "MailSearch", component: MailSearch },
  { name: "MailWarning", component: MailWarning },
  { name: "MailX", component: MailX },
  { name: "Mailbox", component: Mailbox },
  { name: "Mails", component: Mails },
  { name: "Map", component: Map },
  { name: "MapPin", component: MapPin },
  { name: "MapPinOff", component: MapPinOff },
  { name: "MapPinned", component: MapPinned },
  { name: "Martini", component: Martini },
  { name: "Maximize", component: Maximize },
  { name: "Maximize2", component: Maximize2 },
  { name: "Medal", component: Medal },
  { name: "Megaphone", component: Megaphone },
  { name: "MegaphoneOff", component: MegaphoneOff },
  { name: "Meh", component: Meh },
  { name: "MemoryStick", component: MemoryStick },
  { name: "Menu", component: Menu },
  { name: "Merge", component: Merge },
  { name: "MessageCircle", component: MessageCircle },
  { name: "MessageCircleCode", component: MessageCircleCode },
  { name: "MessageCircleDashed", component: MessageCircleDashed },
  { name: "MessageCircleHeart", component: MessageCircleHeart },
  { name: "MessageCircleMore", component: MessageCircleMore },
  { name: "MessageCircleOff", component: MessageCircleOff },
  { name: "MessageCirclePlus", component: MessageCirclePlus },
  { name: "MessageCircleQuestion", component: MessageCircleQuestion },
  { name: "MessageCircleReply", component: MessageCircleReply },
  { name: "MessageCircleWarning", component: MessageCircleWarning },
  { name: "MessageCircleX", component: MessageCircleX },
  { name: "MessageSquare", component: MessageSquare },
  { name: "MessageSquareCode", component: MessageSquareCode },
  { name: "MessageSquareDashed", component: MessageSquareDashed },
  { name: "MessageSquareDiff", component: MessageSquareDiff },
  { name: "MessageSquareDot", component: MessageSquareDot },
  { name: "MessageSquareHeart", component: MessageSquareHeart },
  { name: "MessageSquareMore", component: MessageSquareMore },
  { name: "MessageSquareOff", component: MessageSquareOff },
  { name: "MessageSquarePlus", component: MessageSquarePlus },
  { name: "MessageSquareQuote", component: MessageSquareQuote },
  { name: "MessageSquareReply", component: MessageSquareReply },
  { name: "MessageSquareShare", component: MessageSquareShare },
  { name: "MessageSquareText", component: MessageSquareText },
  { name: "MessageSquareWarning", component: MessageSquareWarning },
  { name: "MessageSquareX", component: MessageSquareX },
  { name: "MessagesSquare", component: MessagesSquare },
  { name: "Mic", component: Mic },
  { name: "MicOff", component: MicOff },
  { name: "MicVocal", component: MicVocal },
  { name: "Microscope", component: Microscope },
  { name: "Microwave", component: Microwave },
  { name: "Milestone", component: Milestone },
  { name: "Milk", component: Milk },
  { name: "MilkOff", component: MilkOff },
  { name: "Minimize", component: Minimize },
  { name: "Minimize2", component: Minimize2 },
  { name: "Minus", component: Minus },
  { name: "Monitor", component: Monitor },
  { name: "MonitorCheck", component: MonitorCheck },
  { name: "MonitorCog", component: MonitorCog },
  { name: "MonitorDot", component: MonitorDot },
  { name: "MonitorDown", component: MonitorDown },
  { name: "MonitorOff", component: MonitorOff },
  { name: "MonitorPause", component: MonitorPause },
  { name: "MonitorPlay", component: MonitorPlay },
  { name: "MonitorSmartphone", component: MonitorSmartphone },
  { name: "MonitorSpeaker", component: MonitorSpeaker },
  { name: "MonitorStop", component: MonitorStop },
  { name: "MonitorUp", component: MonitorUp },
  { name: "MonitorX", component: MonitorX },
  { name: "Moon", component: Moon },
  { name: "MoonStar", component: MoonStar },
  { name: "Mountain", component: Mountain },
  { name: "MountainSnow", component: MountainSnow },
  { name: "Mouse", component: Mouse },
  { name: "MouseOff", component: MouseOff },
  { name: "MousePointer", component: MousePointer },
  { name: "MousePointer2", component: MousePointer2 },
  { name: "MousePointerBan", component: MousePointerBan },
  { name: "MousePointerClick", component: MousePointerClick },
  { name: "Move", component: Move },
  { name: "Move3d", component: Move3d },
  { name: "MoveDiagonal", component: MoveDiagonal },
  { name: "MoveDiagonal2", component: MoveDiagonal2 },
  { name: "MoveDown", component: MoveDown },
  { name: "MoveDownLeft", component: MoveDownLeft },
  { name: "MoveDownRight", component: MoveDownRight },
  { name: "MoveHorizontal", component: MoveHorizontal },
  { name: "MoveLeft", component: MoveLeft },
  { name: "MoveRight", component: MoveRight },
  { name: "MoveUp", component: MoveUp },
  { name: "MoveUpLeft", component: MoveUpLeft },
  { name: "MoveUpRight", component: MoveUpRight },
  { name: "MoveVertical", component: MoveVertical },
  { name: "Music", component: Music },
  { name: "Music2", component: Music2 },
  { name: "Music3", component: Music3 },
  { name: "Music4", component: Music4 },
  { name: "Navigation", component: Navigation },
  { name: "Navigation2", component: Navigation2 },
  { name: "Navigation2Off", component: Navigation2Off },
  { name: "NavigationOff", component: NavigationOff },
  { name: "Network", component: Network },
  { name: "Newspaper", component: Newspaper },
  { name: "Nfc", component: Nfc },
  { name: "Notebook", component: Notebook },
  { name: "NotebookPen", component: NotebookPen },
  { name: "NotebookTabs", component: NotebookTabs },
  { name: "NotebookText", component: NotebookText },
  { name: "NotepadText", component: NotepadText },
  { name: "NotepadTextDashed", component: NotepadTextDashed },
  { name: "Nut", component: Nut },
  { name: "NutOff", component: NutOff },
  { name: "Octagon", component: Octagon },
  { name: "OctagonAlert", component: OctagonAlert },
  { name: "OctagonPause", component: OctagonPause },
  { name: "OctagonX", component: OctagonX },
  { name: "Option", component: Option },
  { name: "Orbit", component: Orbit },
  { name: "Origami", component: Origami },
  { name: "Package", component: Package },
  { name: "Package2", component: Package2 },
  { name: "PackageCheck", component: PackageCheck },
  { name: "PackageMinus", component: PackageMinus },
  { name: "PackageOpen", component: PackageOpen },
  { name: "PackagePlus", component: PackagePlus },
  { name: "PackageSearch", component: PackageSearch },
  { name: "PackageX", component: PackageX },
  { name: "PaintBucket", component: PaintBucket },
  { name: "PaintRoller", component: PaintRoller },
  { name: "Paintbrush", component: Paintbrush },
  { name: "PaintbrushVertical", component: PaintbrushVertical },
  { name: "Palette", component: Palette },
  { name: "PanelBottom", component: PanelBottom },
  { name: "PanelBottomClose", component: PanelBottomClose },
  { name: "PanelBottomDashed", component: PanelBottomDashed },
  { name: "PanelBottomOpen", component: PanelBottomOpen },
  { name: "PanelLeft", component: PanelLeft },
  { name: "PanelLeftClose", component: PanelLeftClose },
  { name: "PanelLeftDashed", component: PanelLeftDashed },
  { name: "PanelLeftOpen", component: PanelLeftOpen },
  { name: "PanelRight", component: PanelRight },
  { name: "PanelRightClose", component: PanelRightClose },
  { name: "PanelRightDashed", component: PanelRightDashed },
  { name: "PanelRightOpen", component: PanelRightOpen },
  { name: "PanelTop", component: PanelTop },
  { name: "PanelTopClose", component: PanelTopClose },
  { name: "PanelTopDashed", component: PanelTopDashed },
  { name: "PanelTopOpen", component: PanelTopOpen },
  { name: "PanelsLeftBottom", component: PanelsLeftBottom },
  { name: "PanelsRightBottom", component: PanelsRightBottom },
  { name: "PanelsTopLeft", component: PanelsTopLeft },
  { name: "Paperclip", component: Paperclip },
  { name: "Parentheses", component: Parentheses },
  { name: "ParkingMeter", component: ParkingMeter },
  { name: "PartyPopper", component: PartyPopper },
  { name: "Pause", component: Pause },
  { name: "PawPrint", component: PawPrint },
  { name: "PcCase", component: PcCase },
  { name: "Pen", component: Pen },
  { name: "PenLine", component: PenLine },
  { name: "PenOff", component: PenOff },
  { name: "PenTool", component: PenTool },
  { name: "Pencil", component: Pencil },
  { name: "PencilLine", component: PencilLine },
  { name: "PencilOff", component: PencilOff },
  { name: "PencilRuler", component: PencilRuler },
  { name: "Pentagon", component: Pentagon },
  { name: "Percent", component: Percent },
  { name: "PersonStanding", component: PersonStanding },
  { name: "PhilippinePeso", component: PhilippinePeso },
  { name: "Phone", component: Phone },
  { name: "PhoneCall", component: PhoneCall },
  { name: "PhoneForwarded", component: PhoneForwarded },
  { name: "PhoneIncoming", component: PhoneIncoming },
  { name: "PhoneMissed", component: PhoneMissed },
  { name: "PhoneOff", component: PhoneOff },
  { name: "PhoneOutgoing", component: PhoneOutgoing },
  { name: "Pi", component: Pi },
  { name: "Piano", component: Piano },
  { name: "Pickaxe", component: Pickaxe },
  { name: "PictureInPicture", component: PictureInPicture },
  { name: "PictureInPicture2", component: PictureInPicture2 },
  { name: "PieChart", component: PieChart },
  { name: "PiggyBank", component: PiggyBank },
  { name: "Pilcrow", component: Pilcrow },
  { name: "PilcrowLeft", component: PilcrowLeft },
  { name: "PilcrowRight", component: PilcrowRight },
  { name: "Pill", component: Pill },
  { name: "PillBottle", component: PillBottle },
  { name: "Pin", component: Pin },
  { name: "PinOff", component: PinOff },
  { name: "Pipette", component: Pipette },
  { name: "Pizza", component: Pizza },
  { name: "Plane", component: Plane },
  { name: "PlaneLanding", component: PlaneLanding },
  { name: "PlaneTakeoff", component: PlaneTakeoff },
  { name: "Play", component: Play },
  { name: "Plug", component: Plug },
  { name: "Plug2", component: Plug2 },
  { name: "PlugZap", component: PlugZap },
  { name: "Plus", component: Plus },
  { name: "Pocket", component: Pocket },
  { name: "PocketKnife", component: PocketKnife },
  { name: "Podcast", component: Podcast },
  { name: "Pointer", component: Pointer },
  { name: "PointerOff", component: PointerOff },
  { name: "Popcorn", component: Popcorn },
  { name: "Popsicle", component: Popsicle },
  { name: "PoundSterling", component: PoundSterling },
  { name: "Power", component: Power },
  { name: "PowerOff", component: PowerOff },
  { name: "Presentation", component: Presentation },
  { name: "Printer", component: Printer },
  { name: "PrinterCheck", component: PrinterCheck },
  { name: "Projector", component: Projector },
  { name: "Proportions", component: Proportions },
  { name: "Puzzle", component: Puzzle },
  { name: "Pyramid", component: Pyramid },
  { name: "QrCode", component: QrCode },
  { name: "Quote", component: Quote },
  { name: "Rabbit", component: Rabbit },
  { name: "Radar", component: Radar },
  { name: "Radiation", component: Radiation },
  { name: "Radical", component: Radical },
  { name: "Radio", component: Radio },
  { name: "RadioReceiver", component: RadioReceiver },
  { name: "RadioTower", component: RadioTower },
  { name: "Radius", component: Radius },
  { name: "RailSymbol", component: RailSymbol },
  { name: "Rainbow", component: Rainbow },
  { name: "Rat", component: Rat },
  { name: "Ratio", component: Ratio },
  { name: "Receipt", component: Receipt },
  { name: "ReceiptCent", component: ReceiptCent },
  { name: "ReceiptEuro", component: ReceiptEuro },
  { name: "ReceiptIndianRupee", component: ReceiptIndianRupee },
  { name: "ReceiptJapaneseYen", component: ReceiptJapaneseYen },
  { name: "ReceiptPoundSterling", component: ReceiptPoundSterling },
  { name: "ReceiptRussianRuble", component: ReceiptRussianRuble },
  { name: "ReceiptSwissFranc", component: ReceiptSwissFranc },
  { name: "ReceiptText", component: ReceiptText },
  { name: "RectangleEllipsis", component: RectangleEllipsis },
  { name: "RectangleHorizontal", component: RectangleHorizontal },
  { name: "RectangleVertical", component: RectangleVertical },
  { name: "Recycle", component: Recycle },
  { name: "Redo", component: Redo },
  { name: "Redo2", component: Redo2 },
  { name: "RedoDot", component: RedoDot },
  { name: "RefreshCcw", component: RefreshCcw },
  { name: "RefreshCcwDot", component: RefreshCcwDot },
  { name: "RefreshCw", component: RefreshCw },
  { name: "RefreshCwOff", component: RefreshCwOff },
  { name: "Refrigerator", component: Refrigerator },
  { name: "Regex", component: Regex },
  { name: "RemoveFormatting", component: RemoveFormatting },
  { name: "Repeat", component: Repeat },
  { name: "Repeat1", component: Repeat1 },
  { name: "Repeat2", component: Repeat2 },
  { name: "Replace", component: Replace },
  { name: "ReplaceAll", component: ReplaceAll },
  { name: "Reply", component: Reply },
  { name: "ReplyAll", component: ReplyAll },
  { name: "Rewind", component: Rewind },
  { name: "Ribbon", component: Ribbon },
  { name: "Rocket", component: Rocket },
  { name: "RockingChair", component: RockingChair },
  { name: "RollerCoaster", component: RollerCoaster },
  { name: "Rotate3d", component: Rotate3d },
  { name: "RotateCcw", component: RotateCcw },
  { name: "RotateCcwSquare", component: RotateCcwSquare },
  { name: "RotateCw", component: RotateCw },
  { name: "RotateCwSquare", component: RotateCwSquare },
  { name: "Route", component: Route },
  { name: "RouteOff", component: RouteOff },
  { name: "Router", component: Router },
  { name: "Rows2", component: Rows2 },
  { name: "Rows3", component: Rows3 },
  { name: "Rows4", component: Rows4 },
  { name: "Rss", component: Rss },
  { name: "Ruler", component: Ruler },
  { name: "RussianRuble", component: RussianRuble },
  { name: "Sailboat", component: Sailboat },
  { name: "Salad", component: Salad },
  { name: "Sandwich", component: Sandwich },
  { name: "Satellite", component: Satellite },
  { name: "SatelliteDish", component: SatelliteDish },
  { name: "Save", component: Save },
  { name: "SaveAll", component: SaveAll },
  { name: "SaveOff", component: SaveOff },
  { name: "Scale", component: Scale },
  { name: "Scale3d", component: Scale3d },
  { name: "Scaling", component: Scaling },
  { name: "Scan", component: Scan },
  { name: "ScanBarcode", component: ScanBarcode },
  { name: "ScanEye", component: ScanEye },
  { name: "ScanFace", component: ScanFace },
  { name: "ScanLine", component: ScanLine },
  { name: "ScanQrCode", component: ScanQrCode },
  { name: "ScanSearch", component: ScanSearch },
  { name: "ScanText", component: ScanText },
  { name: "ScatterChart", component: ScatterChart },
  { name: "School", component: School },
  { name: "Scissors", component: Scissors },
  { name: "ScissorsLineDashed", component: ScissorsLineDashed },
  { name: "ScreenShare", component: ScreenShare },
  { name: "ScreenShareOff", component: ScreenShareOff },
  { name: "Scroll", component: Scroll },
  { name: "ScrollText", component: ScrollText },
  { name: "Search", component: Search },
  { name: "SearchCheck", component: SearchCheck },
  { name: "SearchCode", component: SearchCode },
  { name: "SearchSlash", component: SearchSlash },
  { name: "SearchX", component: SearchX },
  { name: "Section", component: Section },
  { name: "Send", component: Send },
  { name: "SendHorizontal", component: SendHorizontal },
  { name: "SendToBack", component: SendToBack },
  { name: "SeparatorHorizontal", component: SeparatorHorizontal },
  { name: "SeparatorVertical", component: SeparatorVertical },
  { name: "Server", component: Server },
  { name: "ServerCog", component: ServerCog },
  { name: "ServerCrash", component: ServerCrash },
  { name: "ServerOff", component: ServerOff },
  { name: "Settings", component: Settings },
  { name: "Settings2", component: Settings2 },
  { name: "Shapes", component: Shapes },
  { name: "Share", component: Share },
  { name: "Share2", component: Share2 },
  { name: "Sheet", component: Sheet },
  { name: "Shell", component: Shell },
  { name: "Shield", component: Shield },
  { name: "ShieldAlert", component: ShieldAlert },
  { name: "ShieldBan", component: ShieldBan },
  { name: "ShieldCheck", component: ShieldCheck },
  { name: "ShieldEllipsis", component: ShieldEllipsis },
  { name: "ShieldHalf", component: ShieldHalf },
  { name: "ShieldMinus", component: ShieldMinus },
  { name: "ShieldOff", component: ShieldOff },
  { name: "ShieldPlus", component: ShieldPlus },
  { name: "ShieldQuestion", component: ShieldQuestion },
  { name: "ShieldX", component: ShieldX },
  { name: "Ship", component: Ship },
  { name: "ShipWheel", component: ShipWheel },
  { name: "Shirt", component: Shirt },
  { name: "ShoppingBag", component: ShoppingBag },
  { name: "ShoppingBasket", component: ShoppingBasket },
  { name: "ShoppingCart", component: ShoppingCart },
  { name: "Shovel", component: Shovel },
  { name: "ShowerHead", component: ShowerHead },
  { name: "Shrink", component: Shrink },
  { name: "Shrub", component: Shrub },
  { name: "Shuffle", component: Shuffle },
  { name: "Sigma", component: Sigma },
  { name: "Signal", component: Signal },
  { name: "SignalHigh", component: SignalHigh },
  { name: "SignalLow", component: SignalLow },
  { name: "SignalMedium", component: SignalMedium },
  { name: "SignalZero", component: SignalZero },
  { name: "Signature", component: Signature },
  { name: "Signpost", component: Signpost },
  { name: "SignpostBig", component: SignpostBig },
  { name: "Siren", component: Siren },
  { name: "SkipBack", component: SkipBack },
  { name: "SkipForward", component: SkipForward },
  { name: "Skull", component: Skull },
  { name: "Slack", component: Slack },
  { name: "Slash", component: Slash },
  { name: "Slice", component: Slice },
  { name: "SlidersHorizontal", component: SlidersHorizontal },
  { name: "SlidersVertical", component: SlidersVertical },
  { name: "Smartphone", component: Smartphone },
  { name: "SmartphoneCharging", component: SmartphoneCharging },
  { name: "SmartphoneNfc", component: SmartphoneNfc },
  { name: "Smile", component: Smile },
  { name: "SmilePlus", component: SmilePlus },
  { name: "Snail", component: Snail },
  { name: "Snowflake", component: Snowflake },
  { name: "Sofa", component: Sofa },
  { name: "Soup", component: Soup },
  { name: "Space", component: Space },
  { name: "Spade", component: Spade },
  { name: "Sparkle", component: Sparkle },
  { name: "Sparkles", component: Sparkles },
  { name: "Speaker", component: Speaker },
  { name: "Speech", component: Speech },
  { name: "SpellCheck", component: SpellCheck },
  { name: "SpellCheck2", component: SpellCheck2 },
  { name: "Spline", component: Spline },
  { name: "Split", component: Split },
  { name: "SprayCan", component: SprayCan },
  { name: "Sprout", component: Sprout },
  { name: "Square", component: Square },
  { name: "SquareActivity", component: SquareActivity },
  { name: "SquareArrowDown", component: SquareArrowDown },
  { name: "SquareArrowDownLeft", component: SquareArrowDownLeft },
  { name: "SquareArrowDownRight", component: SquareArrowDownRight },
  { name: "SquareArrowLeft", component: SquareArrowLeft },
  { name: "SquareArrowOutDownLeft", component: SquareArrowOutDownLeft },
  { name: "SquareArrowOutDownRight", component: SquareArrowOutDownRight },
  { name: "SquareArrowOutUpLeft", component: SquareArrowOutUpLeft },
  { name: "SquareArrowOutUpRight", component: SquareArrowOutUpRight },
  { name: "SquareArrowRight", component: SquareArrowRight },
  { name: "SquareArrowUp", component: SquareArrowUp },
  { name: "SquareArrowUpLeft", component: SquareArrowUpLeft },
  { name: "SquareArrowUpRight", component: SquareArrowUpRight },
  { name: "SquareAsterisk", component: SquareAsterisk },
  {
    name: "SquareBottomDashedScissors",
    component: SquareBottomDashedScissors,
  },
  { name: "SquareCheck", component: SquareCheck },
  { name: "SquareCheckBig", component: SquareCheckBig },
  { name: "SquareChevronDown", component: SquareChevronDown },
  { name: "SquareChevronLeft", component: SquareChevronLeft },
  { name: "SquareChevronRight", component: SquareChevronRight },
  { name: "SquareChevronUp", component: SquareChevronUp },
  { name: "SquareCode", component: SquareCode },
  { name: "SquareDashedBottom", component: SquareDashedBottom },
  { name: "SquareDashedBottomCode", component: SquareDashedBottomCode },
  { name: "SquareDashedKanban", component: SquareDashedKanban },
  { name: "SquareDashedMousePointer", component: SquareDashedMousePointer },
  { name: "SquareDivide", component: SquareDivide },
  { name: "SquareDot", component: SquareDot },
  { name: "SquareEqual", component: SquareEqual },
  { name: "SquareFunction", component: SquareFunction },
  { name: "SquareGanttChart", component: SquareGanttChart },
  { name: "SquareKanban", component: SquareKanban },
  { name: "SquareLibrary", component: SquareLibrary },
  { name: "SquareM", component: SquareM },
  { name: "SquareMenu", component: SquareMenu },
  { name: "SquareMinus", component: SquareMinus },
  { name: "SquareMousePointer", component: SquareMousePointer },
  { name: "SquareParking", component: SquareParking },
  { name: "SquareParkingOff", component: SquareParkingOff },
  { name: "SquarePen", component: SquarePen },
  { name: "SquarePercent", component: SquarePercent },
  { name: "SquarePi", component: SquarePi },
  { name: "SquarePilcrow", component: SquarePilcrow },
  { name: "SquarePlay", component: SquarePlay },
  { name: "SquarePlus", component: SquarePlus },
  { name: "SquarePower", component: SquarePower },
  { name: "SquareRadical", component: SquareRadical },
  { name: "SquareScissors", component: SquareScissors },
  { name: "SquareSigma", component: SquareSigma },
  { name: "SquareSlash", component: SquareSlash },
  { name: "SquareSplitHorizontal", component: SquareSplitHorizontal },
  { name: "SquareSplitVertical", component: SquareSplitVertical },
  { name: "SquareStack", component: SquareStack },
  { name: "SquareTerminal", component: SquareTerminal },
  { name: "SquareUser", component: SquareUser },
  { name: "SquareUserRound", component: SquareUserRound },
  { name: "SquareX", component: SquareX },
  { name: "Squircle", component: Squircle },
  { name: "Squirrel", component: Squirrel },
  { name: "Stamp", component: Stamp },
  { name: "Star", component: Star },
  { name: "StarHalf", component: StarHalf },
  { name: "StarOff", component: StarOff },
  { name: "StepBack", component: StepBack },
  { name: "StepForward", component: StepForward },
  { name: "Stethoscope", component: Stethoscope },
  { name: "Sticker", component: Sticker },
  { name: "StickyNote", component: StickyNote },
  { name: "Store", component: Store },
  { name: "StretchHorizontal", component: StretchHorizontal },
  { name: "StretchVertical", component: StretchVertical },
  { name: "Strikethrough", component: Strikethrough },
  { name: "Subscript", component: Subscript },
  { name: "Sun", component: Sun },
  { name: "SunDim", component: SunDim },
  { name: "SunMedium", component: SunMedium },
  { name: "SunMoon", component: SunMoon },
  { name: "SunSnow", component: SunSnow },
  { name: "Sunrise", component: Sunrise },
  { name: "Sunset", component: Sunset },
  { name: "Superscript", component: Superscript },
  { name: "SwatchBook", component: SwatchBook },
  { name: "SwissFranc", component: SwissFranc },
  { name: "SwitchCamera", component: SwitchCamera },
  { name: "Sword", component: Sword },
  { name: "Swords", component: Swords },
  { name: "Syringe", component: Syringe },
  { name: "Table", component: Table },
  { name: "Table2", component: Table2 },
  { name: "TableCellsMerge", component: TableCellsMerge },
  { name: "TableCellsSplit", component: TableCellsSplit },
  { name: "TableColumnsSplit", component: TableColumnsSplit },
  { name: "TableProperties", component: TableProperties },
  { name: "TableRowsSplit", component: TableRowsSplit },
  { name: "Tablet", component: Tablet },
  { name: "TabletSmartphone", component: TabletSmartphone },
  { name: "Tablets", component: Tablets },
  { name: "Tag", component: Tag },
  { name: "Tags", component: Tags },
  { name: "Tally1", component: Tally1 },
  { name: "Tally2", component: Tally2 },
  { name: "Tally3", component: Tally3 },
  { name: "Tally4", component: Tally4 },
  { name: "Tally5", component: Tally5 },
  { name: "Tangent", component: Tangent },
  { name: "Target", component: Target },
  { name: "Telescope", component: Telescope },
  { name: "Tent", component: Tent },
  { name: "TentTree", component: TentTree },
  { name: "Terminal", component: Terminal },
  { name: "TestTube", component: TestTube },
  { name: "TestTubeDiagonal", component: TestTubeDiagonal },
  { name: "TestTubes", component: TestTubes },
  { name: "Text", component: Text },
  { name: "TextCursor", component: TextCursor },
  { name: "TextCursorInput", component: TextCursorInput },
  { name: "TextQuote", component: TextQuote },
  { name: "TextSearch", component: TextSearch },
  { name: "TextSelect", component: TextSelect },
  { name: "Theater", component: Theater },
  { name: "Thermometer", component: Thermometer },
  { name: "ThermometerSnowflake", component: ThermometerSnowflake },
  { name: "ThermometerSun", component: ThermometerSun },
  { name: "ThumbsDown", component: ThumbsDown },
  { name: "ThumbsUp", component: ThumbsUp },
  { name: "Ticket", component: Ticket },
  { name: "TicketCheck", component: TicketCheck },
  { name: "TicketMinus", component: TicketMinus },
  { name: "TicketPercent", component: TicketPercent },
  { name: "TicketPlus", component: TicketPlus },
  { name: "TicketSlash", component: TicketSlash },
  { name: "TicketX", component: TicketX },
  { name: "Timer", component: Timer },
  { name: "TimerOff", component: TimerOff },
  { name: "TimerReset", component: TimerReset },
  { name: "ToggleLeft", component: ToggleLeft },
  { name: "ToggleRight", component: ToggleRight },
  { name: "Tornado", component: Tornado },
  { name: "Torus", component: Torus },
  { name: "Touchpad", component: Touchpad },
  { name: "TouchpadOff", component: TouchpadOff },
  { name: "TowerControl", component: TowerControl },
  { name: "ToyBrick", component: ToyBrick },
  { name: "Tractor", component: Tractor },
  { name: "TrafficCone", component: TrafficCone },
  { name: "TrainFront", component: TrainFront },
  { name: "TrainFrontTunnel", component: TrainFrontTunnel },
  { name: "TrainTrack", component: TrainTrack },
  { name: "TramFront", component: TramFront },
  { name: "Trash", component: Trash },
  { name: "Trash2", component: Trash2 },
  { name: "TreeDeciduous", component: TreeDeciduous },
  { name: "TreePalm", component: TreePalm },
  { name: "TreePine", component: TreePine },
  { name: "Trees", component: Trees },
  { name: "Trello", component: Trello },
  { name: "TrendingDown", component: TrendingDown },
  { name: "TrendingUp", component: TrendingUp },
  { name: "Triangle", component: Triangle },
  { name: "TriangleAlert", component: TriangleAlert },
  { name: "TriangleRight", component: TriangleRight },
  { name: "Trophy", component: Trophy },
  { name: "Truck", component: Truck },
  { name: "Turtle", component: Turtle },
  { name: "Tv", component: Tv },
  { name: "TvMinimal", component: TvMinimal },
  { name: "TvMinimalPlay", component: TvMinimalPlay },
  { name: "Twitch", component: Twitch },
  { name: "Twitter", component: Twitter },
  { name: "Type", component: Type },
  { name: "TypeOutline", component: TypeOutline },
  { name: "Umbrella", component: Umbrella },
  { name: "UmbrellaOff", component: UmbrellaOff },
  { name: "Underline", component: Underline },
  { name: "Undo", component: Undo },
  { name: "Undo2", component: Undo2 },
  { name: "UndoDot", component: UndoDot },
  { name: "UnfoldHorizontal", component: UnfoldHorizontal },
  { name: "UnfoldVertical", component: UnfoldVertical },
  { name: "Ungroup", component: Ungroup },
  { name: "University", component: University },
  { name: "Unlink", component: Unlink },
  { name: "Unlink2", component: Unlink2 },
  { name: "Unplug", component: Unplug },
  { name: "Upload", component: Upload },
  { name: "Usb", component: Usb },
  { name: "User", component: User },
  { name: "UserCheck", component: UserCheck },
  { name: "UserCog", component: UserCog },
  { name: "UserMinus", component: UserMinus },
  { name: "UserPen", component: UserPen },
  { name: "UserPlus", component: UserPlus },
  { name: "UserRound", component: UserRound },
  { name: "UserRoundCheck", component: UserRoundCheck },
  { name: "UserRoundCog", component: UserRoundCog },
  { name: "UserRoundMinus", component: UserRoundMinus },
  { name: "UserRoundPen", component: UserRoundPen },
  { name: "UserRoundPlus", component: UserRoundPlus },
  { name: "UserRoundSearch", component: UserRoundSearch },
  { name: "UserRoundX", component: UserRoundX },
  { name: "UserSearch", component: UserSearch },
  { name: "UserX", component: UserX },
  { name: "Users", component: Users },
  { name: "UsersRound", component: UsersRound },
  { name: "Utensils", component: Utensils },
  { name: "UtensilsCrossed", component: UtensilsCrossed },
  { name: "UtilityPole", component: UtilityPole },
  { name: "Variable", component: Variable },
  { name: "Vault", component: Vault },
  { name: "Vegan", component: Vegan },
  { name: "VenetianMask", component: VenetianMask },
  { name: "Vibrate", component: Vibrate },
  { name: "VibrateOff", component: VibrateOff },
  { name: "Video", component: Video },
  { name: "VideoOff", component: VideoOff },
  { name: "Videotape", component: Videotape },
  { name: "View", component: View },
  { name: "Voicemail", component: Voicemail },
  { name: "Volume", component: Volume },
  { name: "Volume1", component: Volume1 },
  { name: "Volume2", component: Volume2 },
  { name: "VolumeX", component: VolumeX },
  { name: "Vote", component: Vote },
  { name: "Wallet", component: Wallet },
  { name: "WalletCards", component: WalletCards },
  { name: "WalletMinimal", component: WalletMinimal },
  { name: "Wallpaper", component: Wallpaper },
  { name: "Wand", component: Wand },
  { name: "WandSparkles", component: WandSparkles },
  { name: "Warehouse", component: Warehouse },
  { name: "WashingMachine", component: WashingMachine },
  { name: "Watch", component: Watch },
  { name: "Waves", component: Waves },
  { name: "Waypoints", component: Waypoints },
  { name: "Webcam", component: Webcam },
  { name: "Webhook", component: Webhook },
  { name: "WebhookOff", component: WebhookOff },
  { name: "Weight", component: Weight },
  { name: "Wheat", component: Wheat },
  { name: "WheatOff", component: WheatOff },
  { name: "WholeWord", component: WholeWord },
  { name: "Wifi", component: Wifi },
  { name: "WifiHigh", component: WifiHigh },
  { name: "WifiLow", component: WifiLow },
  { name: "WifiOff", component: WifiOff },
  { name: "WifiZero", component: WifiZero },
  { name: "Wind", component: Wind },
  { name: "Wine", component: Wine },
  { name: "WineOff", component: WineOff },
  { name: "Workflow", component: Workflow },
  { name: "Worm", component: Worm },
  { name: "WrapText", component: WrapText },
  { name: "Wrench", component: Wrench },
  { name: "X", component: X },
  { name: "Youtube", component: Youtube },
  { name: "Zap", component: Zap },
  { name: "ZapOff", component: ZapOff },
  { name: "ZoomIn", component: ZoomIn },
  { name: "ZoomOut", component: ZoomOut },
];
